/* Personal breaks: create from a free day slot, edit/delete from calendar. */
(function(){
 const FN='resnitsy-dayoff', U='https://acukaqoguzkrphauovhk.supabase.co/functions/v1/'+FN;
 async function breakApi(action,payload={}){const r=await fetch(U,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:PIN,action,...payload})});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw Error(j.error||'Ошибка');return j}
 function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function timeOf(iso){return new Date(iso).toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'})}
 window.chooseSlotAction=function(date,time){modal('Что добавить?',date+' · '+time,`<button class="btn primary" id="slotClient">Записать клиента</button><button class="btn" id="slotBreak">Перерыв / личное дело</button>`,`<button class="btn" id="slotCancel">Отмена</button>`);document.getElementById('slotClient').onclick=()=>{closeModal();form(null,date,time)};document.getElementById('slotBreak').onclick=()=>breakForm(null,date,time);document.getElementById('slotCancel').onclick=closeModal}
 window.breakForm=function(row,date,time){const st=row?timeOf(row.starts_at):time;let end;if(row)end=timeOf(row.ends_at);else{const [h,m]=st.split(':').map(Number),d=new Date(2000,0,1,h,m+60);end=String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}const ds=row?new Date(row.starts_at).toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'}):date;modal(row?'Перерыв':'Создать перерыв','Личное дело не попадёт в клиентов и финансы',`<label>Дата<input id="brDate" type="date" value="${ds}"></label><div class="grid2"><label>Начало<input id="brStart" type="time" step="900" value="${st}"></label><label>Конец<input id="brEnd" type="time" step="900" value="${end}"></label></div><label>Комментарий<textarea id="brNote" placeholder="Например: врач, обед, личные дела">${esc(row?.label||'')}</textarea></label>`,`<button class="btn primary" id="brSave">Сохранить</button>${row?'<button class="btn danger" id="brDelete">Удалить</button>':''}<button class="btn" id="brClose">Отмена</button>`);document.getElementById('brClose').onclick=closeModal;document.getElementById('brSave').onclick=async()=>{try{await breakApi(row?'updateBreak':'createBreak',{id:row?.id,date:document.getElementById('brDate').value,start:document.getElementById('brStart').value,end:document.getElementById('brEnd').value,label:document.getElementById('brNote').value});closeModal();renderCal()}catch(e){alert(e.message)}};if(row)document.getElementById('brDelete').onclick=async()=>{if(!confirm('Удалить перерыв?'))return;try{await breakApi('deleteBreak',{id:row.id});closeModal();renderCal()}catch(e){alert(e.message)}}}
 async function drawBreaks(){if(view!=='day')return;const canvas=document.querySelector('#dayview .day-canvas');if(!canvas)return;try{const z=await breakApi('listBreaks',{from:focus,to:focus});for(const b of z.rows||[]){const st=timeOf(b.starts_at),en=timeOf(b.ends_at),[sh,sm]=st.split(':').map(Number),[eh,em]=en.split(':').map(Number),start=8,rowH=64,mins=sh*60+sm,dur=Math.max(15,eh*60+em-mins),el=document.createElement('button');el.className='day-break';el.style.top=((mins-start*60)/60*rowH)+'px';el.style.height=Math.max(30,dur/60*rowH)+'px';el.innerHTML='<strong>'+st+'–'+en+' · Перерыв</strong><small>'+esc(b.label||'Личное дело')+'</small>';el.onclick=e=>{e.stopPropagation();breakForm(b)};canvas.appendChild(el)}}catch(e){console.warn('breaks',e)}}
 const prev=window.renderDayV4;if(typeof prev==='function')window.renderDayV4=async function(){const x=await prev.apply(this,arguments);await drawBreaks();return x};
})();