/* Personal breaks: create from a free day slot, edit/delete from calendar. */
(function(){
 const U='https://acukaqoguzkrphauovhk.supabase.co/functions/v1/resnitsy-break';
 async function breakApi(action,payload={}){const r=await fetch(U,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:PIN,action,...payload})});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw Error(j.error||'Ошибка');return j}
 function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function timeOf(iso){return new Date(iso).toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'})}
 function iso(ds,t){return new Date(ds+'T'+t+':00+03:00').toISOString()}
 window.chooseSlotAction=function(date,time){modal('Что добавить?',date+' · '+time,`<div class="break-choice"><button class="btn primary" id="slotClient">Записать клиента</button><button class="btn" id="slotBreak">Перерыв / личное дело</button></div>`,`<button class="btn" id="slotCancel">Отмена</button>`);document.getElementById('slotClient').onclick=()=>{closeModal();form(null,date,time)};document.getElementById('slotBreak').onclick=()=>breakForm(null,date,time);document.getElementById('slotCancel').onclick=closeModal}
 window.breakForm=function(row,date,time){const st=row?timeOf(row.starts_at):time;let end;if(row)end=timeOf(row.ends_at);else{const [h,m]=st.split(':').map(Number),d=new Date(2000,0,1,h,m+60);end=String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}const ds=row?new Date(row.starts_at).toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'}):date;modal(row?'Перерыв':'Создать перерыв','Личное дело не попадёт в клиентов и финансы',`<div class="break-form"><label class="break-field"><span>Дата</span><input id="brDate" type="date" value="${ds}"></label><div class="break-times"><label class="break-field"><span>Начало</span><input id="brStart" type="time" step="900" value="${st}"></label><label class="break-field"><span>Конец</span><input id="brEnd" type="time" step="900" value="${end}"></label></div><label class="break-field break-comment"><span>Комментарий</span><textarea id="brNote" maxlength="1000" rows="7" placeholder="Например: врач, обед, забрать машину, личные дела…">${esc(row?.label||'')}</textarea><small><span id="brCount">${String(row?.label||'').length}</span>/1000</small></label></div>`,`<button class="btn primary" id="brSave">Сохранить</button>${row?'<button class="btn danger" id="brDelete">Удалить</button>':''}<button class="btn" id="brClose">Отмена</button>`);const note=document.getElementById('brNote'),count=document.getElementById('brCount');note.oninput=()=>count.textContent=note.value.length;document.getElementById('brClose').onclick=closeModal;document.getElementById('brSave').onclick=async()=>{try{const d=document.getElementById('brDate').value,s=document.getElementById('brStart').value,e=document.getElementById('brEnd').value;await breakApi('save',{id:row?.id,starts_at:iso(d,s),ends_at:iso(d,e),comment:note.value});closeModal();renderCal()}catch(e){alert(e.message)}};if(row)document.getElementById('brDelete').onclick=async()=>{if(!confirm('Удалить перерыв?'))return;try{await breakApi('delete',{id:row.id});closeModal();renderCal()}catch(e){alert(e.message)}}}
 async function drawBreaks(){if(view!=='day')return;const canvas=document.querySelector('#dayview .day-canvas');if(!canvas||!window.lastCal)return;for(const b of (lastCal.blocks||[]).filter(x=>x.source==='manual_break')){const st=timeOf(b.starts_at),en=timeOf(b.ends_at),[sh,sm]=st.split(':').map(Number),[eh,em]=en.split(':').map(Number),start=8,rowH=64,mins=sh*60+sm,dur=Math.max(15,eh*60+em-mins),el=document.createElement('button');el.className='day-break';el.style.top=((mins-start*60)/60*rowH)+'px';el.style.height=Math.max(30,dur/60*rowH)+'px';el.innerHTML='<strong>'+st+'–'+en+' · Перерыв</strong><small>'+esc(b.label||'Личное дело')+'</small>';el.onclick=e=>{e.stopPropagation();breakForm(b)};canvas.appendChild(el)}}
 const prev=window.renderDayV4;if(typeof prev==='function')window.renderDayV4=async function(){const x=await prev.apply(this,arguments);await drawBreaks();return x};
})();