/* Full-day off controls */
const DAYOFF_EDGE='https://acukaqoguzkrphauovhk.supabase.co/functions/v1/resnitsy-dayoff';
async function dayoffApi(action,data={}){const r=await fetch(DAYOFF_EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:PIN,action,...data})});const j=await r.json();if(!r.ok||!j.ok){const e=new Error(j.error||'Ошибка выходного дня');e.payload=j;throw e}return j}
function isDayOff(cal,ds){const st=new Date(ds+'T00:00:00+03:00'),en=new Date(ds+'T23:59:59+03:00');return (cal?.blocks||[]).some(b=>b.label==='Выходной'&&new Date(b.starts_at)<=en&&new Date(b.ends_at)>st)}
async function toggleDayOff(ds,currently){
  if(currently){if(!confirm('Вернуть '+new Date(ds+'T00:00:00').toLocaleDateString('ru-RU')+' в рабочие дни?'))return;await dayoffApi('unset',{date:ds});await renderCal();return}
  try{await dayoffApi('set',{date:ds})}
  catch(e){if(e.payload?.needs_confirm){const names=(e.payload.appointments||[]).map(a=>new Date(a.starts_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'})+' '+(a.clients?.display_name||'клиент')).join('\n');if(!confirm('На этот день уже есть записи:\n'+names+'\n\nВсё равно сделать день выходным? Записи останутся в календаре.'))return;await dayoffApi('set',{date:ds,force:true})}else throw e}
  await renderCal();
}
const _renderWeekV4_dayoff=renderWeekV4;
renderWeekV4=async function(){await _renderWeekV4_dayoff();const cal=lastCal;[...document.querySelectorAll('#week .day')].forEach((col,i)=>{const ds=add(weekStart,i),off=isDayOff(cal,ds),dh=col.querySelector('.dh');if(!dh)return;col.classList.toggle('day-off',off);if(off){col.querySelectorAll('.free').forEach(x=>x.style.display='none');const mark=document.createElement('div');mark.className='dayoff-mark';mark.textContent='ВЫХОДНОЙ';col.appendChild(mark)}const b=document.createElement('button');b.type='button';b.className='dayoff-mini';b.textContent=off?'↻':'В';b.title=off?'Вернуть рабочий день':'Сделать выходным';b.onclick=e=>{e.stopPropagation();toggleDayOff(ds,off)};dh.appendChild(b)});};
const _renderDayV4_dayoff=renderDayV4;
renderDayV4=async function(){await _renderDayV4_dayoff();const from=new Date(focus+'T00:00:00+03:00').toISOString(),to=new Date(add(focus,1)+'T00:00:00+03:00').toISOString(),cal=await rpc('master_app_calendar',{p_pin:PIN,p_from:from,p_to:to}),off=isDayOff(cal,focus),dv=document.getElementById('dayview');if(off){dv.classList.add('day-off-view');dv.querySelectorAll('.day-slot').forEach(x=>x.style.display='none')}const bar=document.createElement('div');bar.className='dayoff-daybar';bar.innerHTML='<button type="button" class="btn '+(off?'':'primary')+'" id="dayoffDayBtn">'+(off?'Вернуть рабочий день':'Сделать весь день выходным')+'</button>';dv.insertBefore(bar,dv.firstChild);document.getElementById('dayoffDayBtn').onclick=()=>toggleDayOff(focus,off);};
const _renderSettings_dayoff=renderSettings;
renderSettings=async function(){_renderSettings_dayoff();const box=document.getElementById('settingsBox'),card=document.createElement('div');card.className='card';card.innerHTML='<b>Выходные дни</b><div class="sub">Закрыть один день или диапазон целиком</div><div class="twocol"><div class="field"><label>С</label><input id="dayoffFrom" type="date" value="'+todayStr()+'"></div><div class="field"><label>По</label><input id="dayoffTo" type="date" value="'+todayStr()+'"></div></div><button class="btn primary" id="dayoffAddRange" style="width:100%">Добавить выходные</button><div id="dayoffList" class="list" style="margin-top:8px"></div>';box.appendChild(card);document.getElementById('dayoffAddRange').onclick=async()=>{const f=document.getElementById('dayoffFrom').value,t=document.getElementById('dayoffTo').value;if(!f||!t||f>t)return alert('Проверьте даты');let d=f;while(d<=t){try{await dayoffApi('set',{date:d})}catch(e){if(e.payload?.needs_confirm){if(confirm('На '+new Date(d+'T00:00:00').toLocaleDateString('ru-RU')+' есть записи. Всё равно сделать выходным?'))await dayoffApi('set',{date:d,force:true})}}d=add(d,1)}await loadDayoffList()};await loadDayoffList();};
async function loadDayoffList(){const host=document.getElementById('dayoffList');if(!host)return;host.innerHTML='<div class="sub">Загрузка…</div>';const z=await dayoffApi('list',{from:add(todayStr(),-30),to:add(todayStr(),365)}),rows=z.rows||[];host.innerHTML=rows.length?rows.map(r=>{const ds=new Date(r.starts_at).toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'});return '<div class="card" style="display:flex;justify-content:space-between;align-items:center"><span><b>'+new Date(r.starts_at).toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'long',timeZone:'Europe/Moscow'})+'</b><div class="sub">Выходной</div></span><button class="btn dayoffRemove" data-date="'+ds+'">Вернуть</button></div>'}).join(''):'<div class="sub">Выходные пока не добавлены</div>';host.querySelectorAll('.dayoffRemove').forEach(b=>b.onclick=async()=>{await dayoffApi('unset',{date:b.dataset.date});await loadDayoffList()});}
