/* Full-day off controls: recurring weekly schedule + one-off dates */
const DAYOFF_EDGE='https://acukaqoguzkrphauovhk.supabase.co/functions/v1/resnitsy-dayoff';
let weeklyWorkdays=[0,1,2,3,4,5,6];
async function dayoffApi(action,data={}){const r=await fetch(DAYOFF_EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:PIN,action,...data})});const j=await r.json();if(!r.ok||!j.ok){const e=new Error(j.error||'Ошибка выходного дня');e.payload=j;throw e}return j}
async function loadWeeklySchedule(){try{const z=await dayoffApi('weekly');weeklyWorkdays=Array.isArray(z.weekdays)?z.weekdays:[0,1,2,3,4,5,6]}catch{weeklyWorkdays=[0,1,2,3,4,5,6]}}
function weekdayOf(ds){return new Date(ds+'T12:00:00+03:00').getDay()}
function isWeeklyOff(ds){return !weeklyWorkdays.includes(weekdayOf(ds))}
function isManualDayOff(cal,ds){const st=new Date(ds+'T00:00:00+03:00'),en=new Date(ds+'T23:59:59+03:00');return (cal?.blocks||[]).some(b=>b.label==='Выходной'&&new Date(b.starts_at)<=en&&new Date(b.ends_at)>st)}
function isDayOff(cal,ds){return isWeeklyOff(ds)||isManualDayOff(cal,ds)}
async function toggleDayOff(ds,currently){
  if(isWeeklyOff(ds)){alert('Этот день недели отмечен как регулярный выходной. Измените его в Настройки → Регулярные выходные.');return}
  if(currently){if(!confirm('Вернуть '+new Date(ds+'T00:00:00').toLocaleDateString('ru-RU')+' в рабочие дни?'))return;await dayoffApi('unset',{date:ds});await renderCal();return}
  try{await dayoffApi('set',{date:ds})}
  catch(e){if(e.payload?.needs_confirm){const names=(e.payload.appointments||[]).map(a=>new Date(a.starts_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'})+' '+(a.clients?.display_name||'клиент')).join('\n');if(!confirm('На этот день уже есть записи:\n'+names+'\n\nВсё равно сделать день выходным? Записи останутся в календаре.'))return;await dayoffApi('set',{date:ds,force:true})}else throw e}
  await renderCal();
}
const _renderWeekV4_dayoff=renderWeekV4;
renderWeekV4=async function(){await loadWeeklySchedule();await _renderWeekV4_dayoff();const cal=lastCal;[...document.querySelectorAll('#week .day')].forEach((col,i)=>{const ds=add(weekStart,i),weekly=isWeeklyOff(ds),off=isDayOff(cal,ds),dh=col.querySelector('.dh');if(!dh)return;col.classList.toggle('day-off',off);if(off){col.querySelectorAll('.free').forEach(x=>x.style.display='none');const mark=document.createElement('div');mark.className='dayoff-mark';mark.textContent=weekly?'ВЫХОДНОЙ ПО ГРАФИКУ':'ВЫХОДНОЙ';col.appendChild(mark)}const b=document.createElement('button');b.type='button';b.className='dayoff-mini';b.textContent=weekly?'•':(off?'↻':'В');b.title=weekly?'Регулярный выходной — меняется в настройках':(off?'Вернуть рабочий день':'Сделать выходным');b.onclick=e=>{e.stopPropagation();toggleDayOff(ds,off)};dh.appendChild(b)});};
const _renderDayV4_dayoff=renderDayV4;
renderDayV4=async function(){await loadWeeklySchedule();await _renderDayV4_dayoff();const from=new Date(focus+'T00:00:00+03:00').toISOString(),to=new Date(add(focus,1)+'T00:00:00+03:00').toISOString(),cal=await rpc('master_app_calendar',{p_pin:PIN,p_from:from,p_to:to}),weekly=isWeeklyOff(focus),off=isDayOff(cal,focus),dv=document.getElementById('dayview');if(off){dv.classList.add('day-off-view');dv.querySelectorAll('.day-slot').forEach(x=>x.style.display='none')}const bar=document.createElement('div');bar.className='dayoff-daybar';bar.innerHTML=weekly?'<div class="card" style="width:100%;text-align:center"><b>Выходной по недельному графику</b><div class="sub">Изменяется в Настройках</div></div>':'<button type="button" class="btn '+(off?'':'primary')+'" id="dayoffDayBtn">'+(off?'Вернуть рабочий день':'Сделать весь день выходным')+'</button>';dv.insertBefore(bar,dv.firstChild);const btn=document.getElementById('dayoffDayBtn');if(btn)btn.onclick=()=>toggleDayOff(focus,off);};
const _renderSettings_dayoff=renderSettings;
renderSettings=async function(){_renderSettings_dayoff();await loadWeeklySchedule();const box=document.getElementById('settingsBox');
 const weekly=document.createElement('div');weekly.className='card';const dayDefs=[[1,'Пн'],[2,'Вт'],[3,'Ср'],[4,'Чт'],[5,'Пт'],[6,'Сб'],[0,'Вс']];weekly.innerHTML='<b>Регулярные выходные</b><div class="sub">Выберите дни недели, в которые вы обычно не работаете</div><div id="weeklyOffDays" style="display:grid;grid-template-columns:repeat(7,1fr);gap:5px;margin-top:10px">'+dayDefs.map(([n,l])=>'<label class="card" style="padding:8px 2px;text-align:center"><input class="weeklyOffCheck" type="checkbox" value="'+n+'" '+(!weeklyWorkdays.includes(n)?'checked':'')+'><br><b>'+l+'</b></label>').join('')+'</div><button class="btn primary" id="weeklyOffSave" style="width:100%;margin-top:8px">Сохранить недельный график</button><div id="weeklyOffMsg" class="sub" style="min-height:18px;margin-top:5px"></div>';box.appendChild(weekly);
 document.getElementById('weeklyOffSave').onclick=async()=>{const btn=document.getElementById('weeklyOffSave'),msg=document.getElementById('weeklyOffMsg'),off=[...document.querySelectorAll('.weeklyOffCheck:checked')].map(x=>Number(x.value)),work=dayDefs.map(x=>x[0]).filter(n=>!off.includes(n));if(!work.length&&!confirm('Вы выбрали выходными все 7 дней. Сохранить?'))return;btn.disabled=true;btn.textContent='Сохраняю…';try{const z=await dayoffApi('setWeekly',{weekdays:work});weeklyWorkdays=z.weekdays;msg.textContent='График сохранён';btn.textContent='Сохранено';setTimeout(()=>{btn.disabled=false;btn.textContent='Сохранить недельный график'},900)}catch(e){msg.textContent=e.message;btn.disabled=false;btn.textContent='Сохранить недельный график'}};
 const card=document.createElement('div');card.className='card';card.innerHTML='<b>Разовые выходные</b><div class="sub">Для отпуска, праздника или отдельного нерабочего дня</div><div class="twocol"><div class="field"><label>С</label><input id="dayoffFrom" type="date" value="'+todayStr()+'"></div><div class="field"><label>По</label><input id="dayoffTo" type="date" value="'+todayStr()+'"></div></div><button class="btn primary" id="dayoffAddRange" style="width:100%">Добавить разовые выходные</button><div id="dayoffList" class="list" style="margin-top:8px"></div>';box.appendChild(card);document.getElementById('dayoffAddRange').onclick=async()=>{const f=document.getElementById('dayoffFrom').value,t=document.getElementById('dayoffTo').value;if(!f||!t||f>t)return alert('Проверьте даты');let d=f;while(d<=t){try{await dayoffApi('set',{date:d})}catch(e){if(e.payload?.needs_confirm){if(confirm('На '+new Date(d+'T00:00:00').toLocaleDateString('ru-RU')+' есть записи. Всё равно сделать выходным?'))await dayoffApi('set',{date:d,force:true})}}d=add(d,1)}await loadDayoffList()};await loadDayoffList();};
async function loadDayoffList(){const host=document.getElementById('dayoffList');if(!host)return;host.innerHTML='<div class="sub">Загрузка…</div>';const z=await dayoffApi('list',{from:add(todayStr(),-30),to:add(todayStr(),365)}),rows=z.rows||[];host.innerHTML=rows.length?rows.map(r=>{const ds=new Date(r.starts_at).toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'});return '<div class="card" style="display:flex;justify-content:space-between;align-items:center"><span><b>'+new Date(r.starts_at).toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'long',timeZone:'Europe/Moscow'})+'</b><div class="sub">Разовый выходной</div></span><button class="btn dayoffRemove" data-date="'+ds+'">Вернуть</button></div>'}).join(''):'<div class="sub">Разовых выходных пока нет</div>';host.querySelectorAll('.dayoffRemove').forEach(b=>b.onclick=async()=>{await dayoffApi('unset',{date:b.dataset.date});await loadDayoffList()});}
