/* Stable notifications settings panel + delivery journal */
const NOTIFY_EDGE='https://acukaqoguzkrphauovhk.supabase.co/functions/v1/resnitsy-notifications';
window.notifyApi=async function(action,data={}){const r=await fetch(NOTIFY_EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:PIN,action,...data})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Ошибка настроек уведомлений');return j};
const notifyApi=window.notifyApi;
function e(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;')}
function nrow(title,sub,id,on){return `<label class="notify-row"><span><b>${title}</b><small>${sub}</small></span><input id="${id}" type="checkbox" ${on?'checked':''}></label>`}
function tpl(title,id,value){return `<details class="notify-template"><summary>${title}</summary><div class="field"><textarea id="${id}" rows="5">${e(value)}</textarea></div><div class="template-actions"><span class="sub template-save-status"></span><button class="btn" type="button" data-save-template>Сохранить шаблон</button></div></details>`}
const journalTypeNames={confirmation:'Подтверждение',reminder:'Напоминание',reminder_day_before:'Напоминание накануне',reminder_hours_before:'Доп. напоминание',reschedule:'Перенос',cancellation:'Отмена',custom:'Сообщение'};
function journalStatus(r){if(r.delivery_status==='sent')return ['Отправлено','ok'];if(r.delivery_status==='sent_manual')return ['Отправлено вручную','manual'];if(r.delivery_status==='failed')return ['Ошибка','bad'];if(r.delivery_status==='shared')return ['Передано вручную','manual'];return ['Подготовлено','wait']}
function journalClient(r){const c=r.clients||{};return c.display_name||c.first_name||'Клиент'}
function journalWhen(r){const d=new Date(r.created_at);return d.toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function journalRow(r){const [st,cls]=journalStatus(r),canRetry=r.delivery_status==='failed';return `<div class="journal-row" data-jid="${e(r.id)}"><div class="journal-top"><div><b>${e(journalClient(r))}</b><div class="sub">${e(journalTypeNames[r.template_type]||r.template_type)} · ${e(journalWhen(r))} · ${e(r.channel||'')}</div></div><span class="journal-status ${cls}">${st}</span></div>${r.error_text?`<div class="journal-error">${e(r.error_text)}</div>`:''}<details class="journal-message"><summary>Текст сообщения</summary><div>${e(r.message_text||'')}</div></details>${Number(r.retry_count||0)>0?`<div class="sub">Повторных попыток: ${Number(r.retry_count)}</div>`:''}<div class="journal-actions">${canRetry?'<button class="btn primary" type="button" data-journal-retry>Отправить вручную</button>':''}<button class="btn" type="button" data-journal-copy>Скопировать</button></div></div>`}
async function loadNotifyJournal(target,status='all'){const box=target.querySelector('#notifyJournalList'),msg=target.querySelector('#notifyJournalMsg');if(!box)return;box.innerHTML='<div class="sub" style="padding:8px">Загрузка журнала…</div>';try{const z=await notifyApi('journal',{status,limit:100}),rows=z.rows||[];box.innerHTML=rows.length?rows.map(journalRow).join(''):'<div class="sub" style="padding:8px">Уведомлений пока нет</div>';const failed=rows.filter(r=>r.delivery_status==='failed').length,sent=rows.filter(r=>r.delivery_status==='sent'||r.delivery_status==='sent_manual').length;msg.textContent=`Показано: ${rows.length} · отправлено: ${sent} · ошибок: ${failed}`;box.querySelectorAll('[data-journal-retry]').forEach(b=>b.onclick=async()=>{const row=b.closest('.journal-row');b.disabled=true;b.textContent='Отправляю…';try{await notifyApi('resendHistory',{historyId:row.dataset.jid});await loadNotifyJournal(target,status)}catch(err){alert(err.message||'Не удалось отправить');b.disabled=false;b.textContent='Отправить вручную'}});box.querySelectorAll('[data-journal-copy]').forEach(b=>b.onclick=async()=>{const row=b.closest('.journal-row'),text=row.querySelector('.journal-message div')?.textContent||'';try{await navigator.clipboard.writeText(text);b.textContent='Скопировано ✓';setTimeout(()=>b.textContent='Скопировать',900)}catch{prompt('Скопируйте сообщение:',text)}})}catch(err){box.innerHTML=`<div class="journal-error">${e(err.message)}</div>`;msg.textContent='Не удалось загрузить журнал'}}
window.renderNotifyPanel=async function(target){target.innerHTML='<div class="sub" style="padding:12px">Загрузка уведомлений…</div>';let z;try{z=await notifyApi('get')}catch(err){target.innerHTML=`<div class="card"><b>Уведомления</b><div class="sub" style="color:#a33;margin-top:6px">${e(err.message)}</div></div>`;return}const n=z.settings||{},st=z.status||{},mp=n.master_push||{},tg=st.telegram_bot||null;target.innerHTML=`<div class="notify-settings-block">
<div class="card"><b>Уведомления</b><div class="sub">Сообщения клиентам и уведомления мастеру</div></div>
<div class="card notify-journal-card"><div class="journal-head"><div><b>Журнал уведомлений</b><div id="notifyJournalMsg" class="sub">Загрузка…</div></div><button class="btn" id="journalRefresh" type="button">↻</button></div><div class="journal-filters"><button class="btn on" type="button" data-journal-filter="all">Все</button><button class="btn" type="button" data-journal-filter="failed">Ошибки</button><button class="btn" type="button" data-journal-filter="sent">Отправленные</button></div><div id="notifyJournalList" class="journal-list"></div></div>
<div class="card telegram-connect"><b>Telegram-бот</b><div class="sub">${tg?`Подключён @${e(tg.bot_username||'')}`:'Подключите своего бота для автоматических сообщений клиентам.'}</div>${tg?`<div class="tg-connected">✓ ${e(tg.bot_name||'Бот подключён')} ${tg.bot_username?'(@'+e(tg.bot_username)+')':''}</div><button class="btn" id="tgDisconnect" type="button">Отключить бота</button>`:`<div class="field"><label>API Token из BotFather</label><input id="tgToken" type="password" autocomplete="off" placeholder="Вставьте токен бота"></div><button class="btn primary" id="tgConnect" type="button" style="width:100%">Подключить Telegram-бота</button>`}<div id="tgMsg" class="sub"></div></div>
<div class="card"><b>Автоуведомления клиентам</b>${nrow('Включить автоуведомления','Главный переключатель','ntEnabled',n.enabled!==false)}<div class="notify-section"><b>События</b>${nrow('Подтверждение записи','После записи или подтверждения мастером','ntConfirmOn',n.confirmation_enabled!==false)}${nrow('Перенос записи','Сообщить о новой дате или времени','ntMoveOn',n.reschedule_enabled!==false)}${nrow('Отмена записи','Сообщить клиенту об отмене','ntCancelOn',n.cancellation_enabled!==false)}</div><div class="notify-section"><b>Напоминания</b>${nrow('Накануне','За день до визита','ntDayBefore',n.reminder_day_before!==false)}<div class="field"><label>Время отправки</label><input id="ntDayTime" type="time" value="${e(n.reminder_day_before_time||'19:00')}"></div>${nrow('Дополнительное напоминание','За несколько часов до визита','ntHoursOn',!!n.reminder_hours_before)}<div class="field"><label>За сколько часов</label><input id="ntHours" type="number" min="1" max="48" value="${Number(n.reminder_hours||3)}"></div></div></div>
<div class="card"><b>Каналы связи</b>${nrow('Telegram',st.telegram_token_configured?'подключён':'не подключён','ntChtelegram',!!n.channels?.telegram)}${nrow('WhatsApp','не подключён','ntChwhatsapp',!!n.channels?.whatsapp)}${nrow('VK','не подключён','ntChvk',!!n.channels?.vk)}${nrow('MAX','не подключён','ntChmax',!!n.channels?.max)}</div>
<div class="card"><b>Уведомления мастеру</b>${nrow('Push-уведомления','Общее включение','mpEnabled',mp.enabled!==false)}${nrow('Новая онлайн-запись','Новая запись клиента','mpNewBooking',mp.new_booking!==false)}${nrow('Изменение записи','Изменились дата, время или услуга','mpChanged',mp.booking_changed!==false)}${nrow('Отмена записи','Клиент отменил запись','mpCancelled',mp.booking_cancelled!==false)}${nrow('Ловец — новая заявка','Новая заявка в ловце','mpWaitNew',mp.waitlist_new!==false)}${nrow('Ловец — ответ клиента','Ответ на предложенное окно','mpWaitResponse',mp.waitlist_response!==false)}${nrow('Сообщение отправлено','Успешная автоотправка','mpMessageSent',!!mp.message_sent)}${nrow('Ошибка отправки','Сообщение не доставлено','mpMessageFailed',mp.message_failed!==false)}${nrow('Ответ техподдержки','Новый ответ по обращению','mpSupportReply',mp.support_reply!==false)}</div>
<div class="card"><b>Шаблоны сообщений</b><div class="sub">Переменные: {name}, {service}, {date}, {time}</div>${tpl('Подтверждение записи','ntConfirm',n.templates?.confirmation)}${tpl('Напоминание','ntReminder',n.templates?.reminder)}${tpl('Перенос записи','ntMove',n.templates?.reschedule)}${tpl('Отмена записи','ntCancel',n.templates?.cancellation)}</div>
<div id="ntMsg" class="sub" style="min-height:20px"></div><button class="btn primary" id="ntSave" style="width:100%">Сохранить все настройки</button>
</div>`;
let journalFilter='all';const setFilter=k=>{journalFilter=k;target.querySelectorAll('[data-journal-filter]').forEach(b=>b.classList.toggle('on',b.dataset.journalFilter===k));loadNotifyJournal(target,k)};target.querySelectorAll('[data-journal-filter]').forEach(b=>b.onclick=()=>setFilter(b.dataset.journalFilter));document.getElementById('journalRefresh').onclick=()=>loadNotifyJournal(target,journalFilter);loadNotifyJournal(target,'all');
const collect=()=>({enabled:document.getElementById('ntEnabled').checked,confirmation_enabled:document.getElementById('ntConfirmOn').checked,reschedule_enabled:document.getElementById('ntMoveOn').checked,cancellation_enabled:document.getElementById('ntCancelOn').checked,reminder_day_before:document.getElementById('ntDayBefore').checked,reminder_day_before_time:document.getElementById('ntDayTime').value,reminder_hours_before:document.getElementById('ntHoursOn').checked,reminder_hours:Number(document.getElementById('ntHours').value||3),channels:{telegram:document.getElementById('ntChtelegram').checked,whatsapp:document.getElementById('ntChwhatsapp').checked,vk:document.getElementById('ntChvk').checked,max:document.getElementById('ntChmax').checked},master_push:{enabled:document.getElementById('mpEnabled').checked,new_booking:document.getElementById('mpNewBooking').checked,booking_changed:document.getElementById('mpChanged').checked,booking_cancelled:document.getElementById('mpCancelled').checked,waitlist_new:document.getElementById('mpWaitNew').checked,waitlist_response:document.getElementById('mpWaitResponse').checked,message_sent:document.getElementById('mpMessageSent').checked,message_failed:document.getElementById('mpMessageFailed').checked,support_reply:document.getElementById('mpSupportReply').checked},templates:{confirmation:document.getElementById('ntConfirm').value,reminder:document.getElementById('ntReminder').value,reschedule:document.getElementById('ntMove').value,cancellation:document.getElementById('ntCancel').value}});
async function save(btn,status){const old=btn.textContent;btn.disabled=true;btn.textContent='Сохраняю…';try{await notifyApi('save',{settings:collect()});btn.textContent='Сохранено ✓';if(status)status.textContent='Сохранено';setTimeout(()=>{btn.disabled=false;btn.textContent=old},900)}catch(err){if(status)status.textContent=err.message;btn.disabled=false;btn.textContent=old}}
document.getElementById('ntSave').onclick=()=>save(document.getElementById('ntSave'),document.getElementById('ntMsg'));target.querySelectorAll('[data-save-template]').forEach(b=>b.onclick=()=>save(b,b.closest('.notify-template').querySelector('.template-save-status')));target.querySelectorAll('textarea').forEach(t=>t.oninput=()=>{t.closest('.notify-template').querySelector('.template-save-status').textContent='Есть несохранённые изменения'});
const c=document.getElementById('tgConnect');if(c)c.onclick=async()=>{const token=document.getElementById('tgToken').value.trim(),m=document.getElementById('tgMsg');if(!token){m.textContent='Вставьте токен из BotFather';return}c.disabled=true;c.textContent='Проверяю…';try{const x=await notifyApi('connectTelegram',{token});m.textContent='Бот @'+(x.bot?.username||'')+' подключён ✓';setTimeout(()=>window.renderNotifyPanel(target),700)}catch(err){m.textContent=err.message;c.disabled=false;c.textContent='Подключить Telegram-бота'}};const d=document.getElementById('tgDisconnect');if(d)d.onclick=async()=>{if(!confirm('Отключить Telegram-бота?'))return;await notifyApi('disconnectTelegram');window.renderNotifyPanel(target)};
};
const style=document.createElement('style');style.textContent='.notify-row{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid var(--line)}.notify-row span{display:flex;flex-direction:column}.notify-row small{color:var(--muted);font-size:10px}.notify-section{border-top:1px solid var(--line);margin-top:10px;padding-top:10px}.notify-template{border-top:1px solid var(--line);padding:10px 0}.notify-template summary{font-weight:700;cursor:pointer}.notify-template textarea{width:100%;min-height:110px}.template-actions{display:flex;align-items:center;justify-content:space-between;gap:10px}.telegram-connect .field{margin-top:10px}.tg-connected{margin:10px 0;padding:10px;border-radius:10px;background:var(--soft);font-weight:700}.notify-settings-block{display:grid;gap:8px}.journal-head,.journal-top,.journal-actions,.journal-filters{display:flex;align-items:center;justify-content:space-between;gap:6px}.journal-filters{justify-content:flex-start;margin:10px 0}.journal-filters .btn{min-height:34px;padding:6px 9px;font-size:11px}.journal-filters .on{background:var(--soft);border-color:var(--accent);font-weight:700}.journal-list{display:grid;gap:7px;max-height:44vh;overflow:auto}.journal-row{border-top:1px solid var(--line);padding:9px 0}.journal-status{font-size:10px;font-weight:700;padding:4px 7px;border-radius:999px;white-space:nowrap}.journal-status.ok{background:#e4f2e5}.journal-status.manual{background:#e8edf7}.journal-status.bad{background:#f7e1e1;color:#8b2c2c}.journal-status.wait{background:#eee}.journal-error{margin:7px 0;padding:7px 8px;border-radius:8px;background:#f8e8e8;color:#8b2c2c;font-size:11px}.journal-message{margin:7px 0;font-size:11px}.journal-message summary{cursor:pointer;color:var(--muted)}.journal-message div{padding-top:5px;white-space:pre-wrap}.journal-actions{justify-content:flex-start;margin-top:7px}.journal-actions .btn{min-height:34px;padding:6px 9px;font-size:11px}';document.head.appendChild(style);
