/* Notification and message settings */
const NOTIFY_EDGE='https://acukaqoguzkrphauovhk.supabase.co/functions/v1/resnitsy-notifications';
async function notifyApi(action,data={}){const r=await fetch(NOTIFY_EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:PIN,action,...data})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Ошибка настроек уведомлений');return j}
const _renderSettings_notify=renderSettings;
renderSettings=async function(){await _renderSettings_notify();const box=document.getElementById('settingsBox');box.querySelectorAll('.notify-settings-block').forEach(x=>x.remove());let z;try{z=await notifyApi('get')}catch(e){const er=document.createElement('div');er.className='card notify-settings-block';er.innerHTML='<b>Уведомления</b><div class="sub" style="color:#a33">'+e.message+'</div>';box.appendChild(er);return}const n=z.settings||{},st=z.status||{},mp=n.master_push||{},tg=st.telegram_bot||null;const card=document.createElement('div');card.className='card notify-settings-block';card.innerHTML=`
<b>Уведомления</b><div class="sub">Автоматические сообщения клиентам и уведомления мастеру</div>
<div class="notify-section telegram-connect"><b>Telegram-бот</b><div class="sub">${tg?'Подключён @'+esc(tg.bot_username||'Telegram bot'):'Подключите своего бота для автоматических сообщений клиентам.'}</div>${tg?`<div class="tg-connected">✓ ${esc(tg.bot_name||'Бот подключён')} ${tg.bot_username?'(@'+esc(tg.bot_username)+')':''}</div><button class="btn" id="tgDisconnect" type="button">Отключить бота</button>`:`<div class="field"><label>API Token из BotFather</label><input id="tgToken" type="password" autocomplete="off" placeholder="Вставьте токен бота"></div><button class="btn primary" id="tgConnect" type="button" style="width:100%">Подключить Telegram-бота</button>`}<div id="tgMsg" class="sub"></div></div>
<label class="notify-row notify-master"><span><b>Автоуведомления клиентам</b><small>Главный переключатель автоматической отправки</small></span><input id="ntEnabled" type="checkbox" ${n.enabled?'checked':''}></label>
<div class="notify-section"><b>События для клиента</b>${row('Подтверждение записи','После онлайн-записи или подтверждения мастером','ntConfirmOn',n.confirmation_enabled!==false)}${row('Перенос записи','Сообщить клиенту о новой дате или времени','ntMoveOn',n.reschedule_enabled!==false)}${row('Отмена записи','Сообщить клиенту об отмене','ntCancelOn',n.cancellation_enabled!==false)}</div>
<div class="notify-section"><b>Напоминания о визите</b>${row('Накануне','Отправить за день до визита','ntDayBefore',n.reminder_day_before)}<div class="field"><label>Время отправки накануне</label><input id="ntDayTime" type="time" value="${n.reminder_day_before_time||'19:00'}"></div>${row('Дополнительное напоминание','За несколько часов до визита','ntHoursOn',n.reminder_hours_before)}<div class="field"><label>За сколько часов</label><input id="ntHours" type="number" min="1" max="48" value="${n.reminder_hours||3}"></div></div>
<div class="notify-section"><b>Каналы связи с клиентом</b><div class="sub">Для автоматической отправки канал должен быть технически подключён.</div>${channelRow('Telegram','telegram',n.channels?.telegram,st.telegram_token_configured)}${channelRow('WhatsApp','whatsapp',n.channels?.whatsapp,st.whatsapp_configured)}${channelRow('VK','vk',n.channels?.vk,st.vk_configured)}${channelRow('MAX','max',n.channels?.max,st.max_configured)}</div>
<div class="notify-section master-push-section"><b>Уведомления мастеру</b><div class="sub">Настройки событий для будущих push-уведомлений приложения.</div><label class="notify-row notify-master"><span><b>Push-уведомления</b><small>Общее включение уведомлений мастеру</small></span><input id="mpEnabled" type="checkbox" ${mp.enabled!==false?'checked':''}></label>${masterPushRow('Новая онлайн-запись','Показать сразу после новой записи клиента','mpNewBooking',mp.new_booking!==false)}${masterPushRow('Изменение записи','Изменились дата, время или услуга','mpChanged',mp.booking_changed!==false)}${masterPushRow('Отмена записи','Клиент отменил запись','mpCancelled',mp.booking_cancelled!==false)}${masterPushRow('Ловец окошек — новая заявка','Клиент добавился в список ожидания','mpWaitNew',mp.waitlist_new!==false)}${masterPushRow('Ловец окошек — ответ клиента','Клиент ответил на предложенное окно','mpWaitResponse',mp.waitlist_response!==false)}${masterPushRow('Сообщение клиенту отправлено','Уведомить об успешной отправке','mpMessageSent',!!mp.message_sent)}${masterPushRow('Ошибка отправки сообщения','Сообщение клиенту не доставлено','mpMessageFailed',mp.message_failed!==false)}${masterPushRow('Ответ техподдержки','Появился ответ по обращению','mpSupportReply',mp.support_reply!==false)}</div>
<div class="notify-section"><b>Шаблоны сообщений</b><div class="sub">Откройте шаблон, измените текст и сохраните. Переменные: {name}, {service}, {date}, {time}</div>${templateBlock('Подтверждение записи','ntConfirm',n.templates?.confirmation,'confirmation')}${templateBlock('Напоминание','ntReminder',n.templates?.reminder,'reminder')}${templateBlock('Перенос записи','ntMove',n.templates?.reschedule,'reschedule')}${templateBlock('Отмена записи','ntCancel',n.templates?.cancellation,'cancellation')}</div>
<div id="ntMsg" class="sub" style="min-height:20px"></div><button class="btn primary" id="ntSave" style="width:100%">Сохранить все настройки</button>`;box.appendChild(card);
const con=document.getElementById('tgConnect');if(con)con.onclick=async()=>{const token=document.getElementById('tgToken').value.trim(),m=document.getElementById('tgMsg');if(!token){m.textContent='Вставьте токен из BotFather';return}con.disabled=true;con.textContent='Проверяю…';try{const x=await notifyApi('connectTelegram',{token});document.getElementById('tgToken').value='';m.textContent='Бот @'+(x.bot?.username||'')+' подключён ✓';setTimeout(()=>renderSettings(),700)}catch(e){m.textContent=e.message;con.disabled=false;con.textContent='Подключить Telegram-бота'}};
const dis=document.getElementById('tgDisconnect');if(dis)dis.onclick=async()=>{if(!confirm('Отключить Telegram-бота?'))return;dis.disabled=true;try{await notifyApi('disconnectTelegram');await renderSettings()}catch(e){document.getElementById('tgMsg').textContent=e.message;dis.disabled=false}};
function collectSettings(){return {enabled:document.getElementById('ntEnabled').checked,confirmation_enabled:document.getElementById('ntConfirmOn').checked,reschedule_enabled:document.getElementById('ntMoveOn').checked,cancellation_enabled:document.getElementById('ntCancelOn').checked,reminder_day_before:document.getElementById('ntDayBefore').checked,reminder_day_before_time:document.getElementById('ntDayTime').value,reminder_hours_before:document.getElementById('ntHoursOn').checked,reminder_hours:Number(document.getElementById('ntHours').value||3),channels:{telegram:document.getElementById('ntChtelegram').checked,whatsapp:document.getElementById('ntChwhatsapp').checked,vk:document.getElementById('ntChvk').checked,max:document.getElementById('ntChmax').checked},master_push:{enabled:document.getElementById('mpEnabled').checked,new_booking:document.getElementById('mpNewBooking').checked,booking_changed:document.getElementById('mpChanged').checked,booking_cancelled:document.getElementById('mpCancelled').checked,waitlist_new:document.getElementById('mpWaitNew').checked,waitlist_response:document.getElementById('mpWaitResponse').checked,message_sent:document.getElementById('mpMessageSent').checked,message_failed:document.getElementById('mpMessageFailed').checked,support_reply:document.getElementById('mpSupportReply').checked},templates:{confirmation:document.getElementById('ntConfirm').value,reminder:document.getElementById('ntReminder').value,reschedule:document.getElementById('ntMove').value,cancellation:document.getElementById('ntCancel').value}}}
async function saveAll(btn,msg){btn.disabled=true;const old=btn.textContent;btn.textContent='Сохраняю…';try{await notifyApi('save',{settings:collectSettings()});btn.textContent='Сохранено ✓';if(msg)msg.textContent='Изменения сохранены';setTimeout(()=>{btn.disabled=false;btn.textContent=old},1100)}catch(e){if(msg)msg.textContent=e.message;btn.disabled=false;btn.textContent=old;throw e}}
document.getElementById('ntSave').onclick=async()=>{try{await saveAll(document.getElementById('ntSave'),document.getElementById('ntMsg'))}catch{}};card.querySelectorAll('[data-save-template]').forEach(btn=>btn.onclick=async()=>{const s=btn.closest('.notify-template')?.querySelector('.template-save-status');try{await saveAll(btn,s)}catch(e){if(s)s.textContent=e.message}});card.querySelectorAll('.notify-template textarea').forEach(t=>t.addEventListener('input',()=>{const s=t.closest('.notify-template')?.querySelector('.template-save-status');if(s)s.textContent='Есть несохранённые изменения'}));
function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;')};function row(a,b,id,on){return `<label class="notify-row"><span><b>${a}</b><small>${b}</small></span><input id="${id}" type="checkbox" ${on?'checked':''}></label>`};function channelRow(name,key,on,connected){return row(name,connected?'подключён':'не подключён','ntCh'+key,on)};function masterPushRow(a,b,id,on){return row(a,b,id,on)};function templateBlock(title,id,value,key){return `<details class="notify-template"><summary>${title}</summary><div class="field"><textarea id="${id}" rows="5">${esc(value)}</textarea></div><div class="template-actions"><span class="sub template-save-status"></span><button class="btn" type="button" data-save-template="${key}">Сохранить шаблон</button></div></details>`}
const style=document.createElement('style');style.textContent='.notify-template{border-top:1px solid var(--line);padding:10px 0}.notify-template summary{cursor:pointer;font-weight:700}.notify-master{background:var(--soft);padding:12px;border-radius:12px;border-bottom:0}.notify-template textarea{width:100%;min-height:110px;resize:vertical}.template-actions{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:7px}.template-actions .sub{flex:1}.telegram-connect{padding:12px;border:1px solid var(--line);border-radius:12px;margin-bottom:12px}.telegram-connect .field{margin-top:10px}.tg-connected{margin:10px 0;padding:10px;border-radius:10px;background:var(--soft);font-weight:700}';document.head.appendChild(style);
