/* Stable notifications settings panel */
const NOTIFY_EDGE='https://acukaqoguzkrphauovhk.supabase.co/functions/v1/resnitsy-notifications';
async function notifyApi(action,data={}){const r=await fetch(NOTIFY_EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:PIN,action,...data})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Ошибка настроек уведомлений');return j}
function e(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;')}
function nrow(title,sub,id,on){return `<label class="notify-row"><span><b>${title}</b><small>${sub}</small></span><input id="${id}" type="checkbox" ${on?'checked':''}></label>`}
function tpl(title,id,value){return `<details class="notify-template"><summary>${title}</summary><div class="field"><textarea id="${id}" rows="5">${e(value)}</textarea></div><div class="template-actions"><span class="sub template-save-status"></span><button class="btn" type="button" data-save-template>Сохранить шаблон</button></div></details>`}
window.renderNotifyPanel=async function(target){target.innerHTML='<div class="sub" style="padding:12px">Загрузка уведомлений…</div>';let z;try{z=await notifyApi('get')}catch(err){target.innerHTML=`<div class="card"><b>Уведомления</b><div class="sub" style="color:#a33;margin-top:6px">${e(err.message)}</div></div>`;return}const n=z.settings||{},st=z.status||{},mp=n.master_push||{},tg=st.telegram_bot||null;target.innerHTML=`<div class="notify-settings-block">
<div class="card"><b>Уведомления</b><div class="sub">Сообщения клиентам и уведомления мастеру</div></div>
<div class="card telegram-connect"><b>Telegram-бот</b><div class="sub">${tg?`Подключён @${e(tg.bot_username||'')}`:'Подключите своего бота для автоматических сообщений клиентам.'}</div>${tg?`<div class="tg-connected">✓ ${e(tg.bot_name||'Бот подключён')} ${tg.bot_username?'(@'+e(tg.bot_username)+')':''}</div><button class="btn" id="tgDisconnect" type="button">Отключить бота</button>`:`<div class="field"><label>API Token из BotFather</label><input id="tgToken" type="password" autocomplete="off" placeholder="Вставьте токен бота"></div><button class="btn primary" id="tgConnect" type="button" style="width:100%">Подключить Telegram-бота</button>`}<div id="tgMsg" class="sub"></div></div>
<div class="card"><b>Автоуведомления клиентам</b>${nrow('Включить автоуведомления','Главный переключатель','ntEnabled',n.enabled!==false)}<div class="notify-section"><b>События</b>${nrow('Подтверждение записи','После записи или подтверждения мастером','ntConfirmOn',n.confirmation_enabled!==false)}${nrow('Перенос записи','Сообщить о новой дате или времени','ntMoveOn',n.reschedule_enabled!==false)}${nrow('Отмена записи','Сообщить клиенту об отмене','ntCancelOn',n.cancellation_enabled!==false)}</div><div class="notify-section"><b>Напоминания</b>${nrow('Накануне','За день до визита','ntDayBefore',n.reminder_day_before!==false)}<div class="field"><label>Время отправки</label><input id="ntDayTime" type="time" value="${e(n.reminder_day_before_time||'19:00')}"></div>${nrow('Дополнительное напоминание','За несколько часов до визита','ntHoursOn',!!n.reminder_hours_before)}<div class="field"><label>За сколько часов</label><input id="ntHours" type="number" min="1" max="48" value="${Number(n.reminder_hours||3)}"></div></div></div>
<div class="card"><b>Каналы связи</b>${nrow('Telegram',st.telegram_token_configured?'подключён':'не подключён','ntChtelegram',!!n.channels?.telegram)}${nrow('WhatsApp','не подключён','ntChwhatsapp',!!n.channels?.whatsapp)}${nrow('VK','не подключён','ntChvk',!!n.channels?.vk)}${nrow('MAX','не подключён','ntChmax',!!n.channels?.max)}</div>
<div class="card"><b>Уведомления мастеру</b>${nrow('Push-уведомления','Общее включение','mpEnabled',mp.enabled!==false)}${nrow('Новая онлайн-запись','Новая запись клиента','mpNewBooking',mp.new_booking!==false)}${nrow('Изменение записи','Изменились дата, время или услуга','mpChanged',mp.booking_changed!==false)}${nrow('Отмена записи','Клиент отменил запись','mpCancelled',mp.booking_cancelled!==false)}${nrow('Ловец — новая заявка','Новая заявка в ловце','mpWaitNew',mp.waitlist_new!==false)}${nrow('Ловец — ответ клиента','Ответ на предложенное окно','mpWaitResponse',mp.waitlist_response!==false)}${nrow('Сообщение отправлено','Успешная автоотправка','mpMessageSent',!!mp.message_sent)}${nrow('Ошибка отправки','Сообщение не доставлено','mpMessageFailed',mp.message_failed!==false)}${nrow('Ответ техподдержки','Новый ответ по обращению','mpSupportReply',mp.support_reply!==false)}</div>
<div class="card"><b>Шаблоны сообщений</b><div class="sub">Переменные: {name}, {service}, {date}, {time}</div>${tpl('Подтверждение записи','ntConfirm',n.templates?.confirmation)}${tpl('Напоминание','ntReminder',n.templates?.reminder)}${tpl('Перенос записи','ntMove',n.templates?.reschedule)}${tpl('Отмена записи','ntCancel',n.templates?.cancellation)}</div>
<div id="ntMsg" class="sub" style="min-height:20px"></div><button class="btn primary" id="ntSave" style="width:100%">Сохранить все настройки</button>
</div>`;
const collect=()=>({enabled:document.getElementById('ntEnabled').checked,confirmation_enabled:document.getElementById('ntConfirmOn').checked,reschedule_enabled:document.getElementById('ntMoveOn').checked,cancellation_enabled:document.getElementById('ntCancelOn').checked,reminder_day_before:document.getElementById('ntDayBefore').checked,reminder_day_before_time:document.getElementById('ntDayTime').value,reminder_hours_before:document.getElementById('ntHoursOn').checked,reminder_hours:Number(document.getElementById('ntHours').value||3),channels:{telegram:document.getElementById('ntChtelegram').checked,whatsapp:document.getElementById('ntChwhatsapp').checked,vk:document.getElementById('ntChvk').checked,max:document.getElementById('ntChmax').checked},master_push:{enabled:document.getElementById('mpEnabled').checked,new_booking:document.getElementById('mpNewBooking').checked,booking_changed:document.getElementById('mpChanged').checked,booking_cancelled:document.getElementById('mpCancelled').checked,waitlist_new:document.getElementById('mpWaitNew').checked,waitlist_response:document.getElementById('mpWaitResponse').checked,message_sent:document.getElementById('mpMessageSent').checked,message_failed:document.getElementById('mpMessageFailed').checked,support_reply:document.getElementById('mpSupportReply').checked},templates:{confirmation:document.getElementById('ntConfirm').value,reminder:document.getElementById('ntReminder').value,reschedule:document.getElementById('ntMove').value,cancellation:document.getElementById('ntCancel').value}});
async function save(btn,status){const old=btn.textContent;btn.disabled=true;btn.textContent='Сохраняю…';try{await notifyApi('save',{settings:collect()});btn.textContent='Сохранено ✓';if(status)status.textContent='Сохранено';setTimeout(()=>{btn.disabled=false;btn.textContent=old},900)}catch(err){if(status)status.textContent=err.message;btn.disabled=false;btn.textContent=old}}
document.getElementById('ntSave').onclick=()=>save(document.getElementById('ntSave'),document.getElementById('ntMsg'));target.querySelectorAll('[data-save-template]').forEach(b=>b.onclick=()=>save(b,b.closest('.notify-template').querySelector('.template-save-status')));target.querySelectorAll('textarea').forEach(t=>t.oninput=()=>{t.closest('.notify-template').querySelector('.template-save-status').textContent='Есть несохранённые изменения'});
const c=document.getElementById('tgConnect');if(c)c.onclick=async()=>{const token=document.getElementById('tgToken').value.trim(),m=document.getElementById('tgMsg');if(!token){m.textContent='Вставьте токен из BotFather';return}c.disabled=true;c.textContent='Проверяю…';try{const x=await notifyApi('connectTelegram',{token});m.textContent='Бот @'+(x.bot?.username||'')+' подключён ✓';setTimeout(()=>window.renderNotifyPanel(target),700)}catch(err){m.textContent=err.message;c.disabled=false;c.textContent='Подключить Telegram-бота'}};const d=document.getElementById('tgDisconnect');if(d)d.onclick=async()=>{if(!confirm('Отключить Telegram-бота?'))return;await notifyApi('disconnectTelegram');window.renderNotifyPanel(target)};
};
const style=document.createElement('style');style.textContent='.notify-row{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid var(--line)}.notify-row span{display:flex;flex-direction:column}.notify-row small{color:var(--muted);font-size:10px}.notify-section{border-top:1px solid var(--line);margin-top:10px;padding-top:10px}.notify-template{border-top:1px solid var(--line);padding:10px 0}.notify-template summary{font-weight:700;cursor:pointer}.notify-template textarea{width:100%;min-height:110px}.template-actions{display:flex;align-items:center;justify-content:space-between;gap:10px}.telegram-connect .field{margin-top:10px}.tg-connected{margin:10px 0;padding:10px;border-radius:10px;background:var(--soft);font-weight:700}.notify-settings-block{display:grid;gap:8px}';document.head.appendChild(style);
