/* Slotelly App v1 — all master-side core actions use local runtime. */
(()=>{
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const localDate=iso=>new Date(iso).toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'});
const localTime=iso=>new Date(iso).toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'});
const cname=c=>c?.display_name||c?.name||'Клиент';
function refreshGlobals(){services=Slotelly.state.services||services||[];settings=Slotelly.state.settings||settings||{};try{categories=settings.service_categories||categories||[]}catch{}}
refreshGlobals();Slotelly.on(()=>{refreshGlobals();if(document.getElementById('calendar')?.classList.contains('on'))renderCal()});
function schedule(){const s=Slotelly.state.settings?.schedule||{};return{weekdays:Array.isArray(s.weekdays)?s.weekdays:[0,1,2,3,4,5,6],groups:Array.isArray(s.work_time_groups)?s.work_time_groups:[],overrides:new Set(Array.isArray(s.workday_overrides)?s.workday_overrides:[])}}
function timesFor(ds,cal){const s=schedule(),dow=new Date(ds+'T12:00:00+03:00').getDay(),g=s.groups.find(x=>(x.days||[]).includes(dow));let times=g?[...(g.times||[])]:[];if(!times.length&&s.weekdays.includes(dow))times=['10:00','13:00','16:00','19:00'];const extra=(cal.overrides||[]).filter(o=>o.is_available&&localDate(o.slot_start)===ds).map(o=>localTime(o.slot_start));return[...new Set([...times,...extra])].sort()}
function dayOff(ds,cal){const s=schedule(),dow=new Date(ds+'T12:00:00+03:00').getDay(),weekly=!s.weekdays.includes(dow)&&!s.overrides.has(ds),st=new Date(ds+'T00:00:00+03:00'),en=new Date(ds+'T23:59:59+03:00');return weekly||(cal.blocks||[]).some(b=>b.label==='Выходной'&&new Date(b.starts_at)<=en&&new Date(b.ends_at)>st)}
function aps(ds){return(Slotelly.calendar().appointments||[]).filter(a=>a.status!=='cancelled'&&localDate(a.starts_at)===ds)}
function blocked(cal,list,ds,t){const st=new Date(ds+'T'+t+':00+03:00'),en=new Date(st.getTime()+30*60000),ov=(cal.overrides||[]).find(o=>new Date(o.slot_start).getTime()===st.getTime());if(ov?.is_available===false)return true;if(list.some(a=>st<new Date(a.ends_at)&&en>new Date(a.starts_at)))return true;return(cal.blocks||[]).some(b=>st<new Date(b.ends_at)&&en>new Date(b.starts_at))}
function renderWeek(){weekStart=monday(weekStart||focus);const cal=Slotelly.calendar(),w=document.getElementById('week'),h=Math.max(420,w.clientHeight||520),today=todayStr();lastCal=cal;document.getElementById('period').textContent=`${ruDate(weekStart,{day:'numeric',month:'short'})} — ${ruDate(add(weekStart,6),{day:'numeric',month:'short',year:'numeric'})}`;w.innerHTML='';for(let i=0;i<7;i++){const ds=add(weekStart,i),off=dayOff(ds,cal),list=aps(ds),col=document.createElement('div');col.className='day'+(off?' day-off':'');col.innerHTML=`<div class="dh ${ds===focus?'selected':''} ${ds===today?'today':''}"><strong>${ruDate(ds,{weekday:'short'}).replace('.','').toUpperCase()}</strong>${ruDate(ds,{day:'numeric'})}</div>`;col.querySelector('.dh').onclick=()=>{focus=ds;view='day';renderCal()};for(const a of list){const st=localTime(a.starts_at),[hh,mm]=st.split(':').map(Number),dur=Math.max(30,(new Date(a.ends_at)-new Date(a.starts_at))/60000),m=hh*60+mm,b=document.createElement('button');b.className='appt '+(a.status||'new')+(a._pending?' pending':'');b.style.top=(42+(m-540)/840*(h-42))+'px';b.style.height=Math.max(24,dur/840*(h-42))+'px';b.innerHTML=`<strong>${st} ${esc(a.client_name||'Клиент')}</strong><small>${esc((a.services||[]).map(s=>s.name).join(' + '))}</small>`;b.onclick=e=>{e.stopPropagation();showAppt(a)};col.appendChild(b)}if(!off)for(const t of timesFor(ds,cal)){if(blocked(cal,list,ds,t))continue;const[hh,mm]=t.split(':').map(Number),m=hh*60+mm,b=document.createElement('button');b.className='free';b.style.top=(42+(m-540)/840*(h-42))+'px';b.textContent=t;b.onclick=e=>{e.stopPropagation();focus=ds;view='day';renderCal()};col.appendChild(b)}w.appendChild(col)}}
function renderDay(){const target=focus,cal=Slotelly.calendar(),dv=document.getElementById('dayview'),start=8,end=22,rowH=64,total=(end-start)*rowH,off=dayOff(target,cal),list=aps(target);lastCal=cal;document.getElementById('period').innerHTML=`<span class="period-weekday">${ruDate(target,{weekday:'long'})}</span><span class="period-date">${ruDate(target,{day:'numeric',month:'long'})}</span>`;const strip=Array.from({length:7},(_,i)=>add(target,i-3)).map(ds=>`<button class="day-date-btn ${ds===target?'on':''}" data-date="${ds}">${ruDate(ds,{weekday:'short'})}<br><b>${ruDate(ds,{day:'numeric'})}</b></button>`).join('');dv.innerHTML=`<div class="day-date-strip">${strip}</div>${off?'<div class="dayoff-status"><b>Выходной</b></div>':''}<div class="day-canvas" style="height:${total}px"></div>`;dv.querySelectorAll('.day-date-btn').forEach(b=>b.onclick=()=>{focus=b.dataset.date;renderCal()});const canvas=dv.querySelector('.day-canvas');for(let h=start;h<=end;h++){const row=document.createElement('div');row.className='day-hour';row.style.top=((h-start)*rowH)+'px';row.innerHTML=`<span class="day-hour-label">${String(h).padStart(2,'0')}:00</span>${h<end?'<span class="day-half-line"></span>':''}`;canvas.appendChild(row)}if(!off)for(const t of timesFor(target,cal)){if(blocked(cal,list,target,t))continue;const[hh,mm]=t.split(':').map(Number);if(hh<start||hh>=end)continue;const b=document.createElement('button');b.className='day-slot available';b.style.top=(((hh*60+mm)-start*60)/60*rowH+2)+'px';b.innerHTML=`<span class="slot-book-time">${t}</span><span class="slot-state-pill on">Доступно</span>`;b.onclick=e=>{e.stopPropagation();form(null,target,t)};canvas.appendChild(b)}for(const a of list){const st=localTime(a.starts_at),[hh,mm]=st.split(':').map(Number),dur=Math.max(30,(new Date(a.ends_at)-new Date(a.starts_at))/60000);if(hh<start||hh>=end)continue;const b=document.createElement('button');b.className='day-appt '+(a.status||'new')+(a._pending?' pending':'');b.style.top=(((hh*60+mm)-start*60)/60*rowH)+'px';b.style.height=Math.max(34,dur/60*rowH)+'px';b.innerHTML=`<strong>${st} · ${esc(a.client_name||'Клиент')}</strong><small>${esc((a.services||[]).map(s=>s.name).join(' + '))}</small>`;b.onclick=()=>showAppt(a);canvas.appendChild(b)}}
window.renderCal=function(){const wt=document.getElementById('weekTab'),dt=document.getElementById('dayTab'),w=document.getElementById('week'),dv=document.getElementById('dayview');wt.classList.toggle('on',view==='week');dt.classList.toggle('on',view==='day');w.style.display=view==='week'?'grid':'none';dv.classList.toggle('on',view==='day');document.getElementById('calSub').textContent=view==='week'?'Неделя целиком':'Выбранный день';view==='week'?renderWeek():renderDay()};
function bind(id,fn){const o=document.getElementById(id);if(!o)return;const n=o.cloneNode(true);o.replaceWith(n);n.onclick=fn}
bind('weekTab',()=>{view='week';weekStart=monday(focus);renderCal()});bind('dayTab',()=>{view='day';renderCal()});bind('prev',()=>{if(view==='week'){weekStart=add(weekStart,-7);focus=weekStart}else focus=add(focus,-1);renderCal();Slotelly.sync(focus,false).catch(()=>{})});bind('next',()=>{if(view==='week'){weekStart=add(weekStart,7);focus=weekStart}else focus=add(focus,1);renderCal();Slotelly.sync(focus,false).catch(()=>{})});bind('todayBtn',()=>{focus=todayStr();weekStart=monday(focus);renderCal()});
window.form=function(a=null,ds=focus,startTime='16:00'){
 let cid=a?.client_id||'',chosenClient=null,rows=a?.services?.length?a.services.map(s=>({service_id:s.service_id||'',name:s.name||'',standard_price:Number(s.standard_price??s.price??0),price:Number(s.price??s.standard_price??0),duration:Number(s.duration??60)})):[{service_id:'',name:'',standard_price:0,price:0,duration:60}];
 const footer=a?'<button class="btn primary" id="save" style="width:100%">Сохранить</button>':'<button class="btn primary" id="save">Сохранить</button><button class="btn" id="newC">+ Новый клиент</button>';
 modal(a?'Редактирование записи':'Новая запись','',`<div class="field"><label>Клиент</label><input id="q" placeholder="Имя или телефон" value="${esc(a?.client_name||'')}" autocomplete="off"></div><div id="res" class="list"></div><div class="twocol"><div class="field"><label>Дата</label><input id="date" type="date" value="${a?localDate(a.starts_at):ds}"></div><div class="field"><label>Время</label><input id="time" type="time" step="900" value="${a?localTime(a.starts_at):startTime}"></div></div><div id="svcRows"></div><button class="btn" id="addSvc" style="width:100%">+ Добавить услугу</button><div class="field"><label>Комментарий</label><textarea id="com">${esc(a?.master_comment||'')}</textarea></div><div id="saveError" class="sub" style="color:#a33;min-height:18px"></div>`,footer);
 const q=document.getElementById('q'),res=document.getElementById('res'),svc=document.getElementById('svcRows'),err=document.getElementById('saveError'),save=document.getElementById('save');
 function rr(){svc.innerHTML='';rows.forEach((r,i)=>{const x=document.createElement('div');x.className='card';x.innerHTML=`<div class="field"><label>Услуга</label><select class="ss"><option value="">— Выберите услугу —</option>${services.filter(s=>s.is_active||s.id===r.service_id).map(s=>`<option value="${s.id}" ${s.id===r.service_id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="twocol"><div class="field"><label>Цена</label><input class="sp" type="number" value="${r.service_id?r.price:''}"></div><div class="field"><label>Длительность, мин</label><input class="sd" type="number" value="${r.service_id?r.duration:''}"></div></div><button type="button" class="btn rm" style="width:100%;color:#a33">Удалить услугу</button>`;const ss=x.querySelector('.ss'),sp=x.querySelector('.sp'),sd=x.querySelector('.sd');ss.onchange=()=>{const s=services.find(z=>z.id===ss.value);rows[i]=s?{service_id:s.id,name:s.name,standard_price:Number(s.base_price||0),price:Number(s.base_price||0),duration:Number(s.duration_minutes||60)}:{service_id:'',name:'',standard_price:0,price:0,duration:60};rr()};sp.oninput=()=>rows[i].price=Number(sp.value||0);sd.oninput=()=>rows[i].duration=Number(sd.value||60);x.querySelector('.rm').onclick=()=>{rows.splice(i,1);if(!rows.length)rows=[{service_id:'',name:'',standard_price:0,price:0,duration:60}];rr()};svc.appendChild(x)})}rr();
 function pick(c){cid=c.id;chosenClient=c;q.value=cname(c);res.innerHTML='';if(!a&&rows.every(r=>!r.service_id)&&Array.isArray(c.last_services)&&c.last_services.length){const mapped=c.last_services.map(s=>{let live=services.find(z=>z.id===s.service_id)||services.find(z=>String(z.name).toLowerCase()===String(s.name).toLowerCase());return live?{service_id:live.id,name:live.name,standard_price:Number(live.base_price||0),price:Number(live.base_price||0),duration:Number(live.duration_minutes||60)}:null}).filter(Boolean);if(mapped.length){rows=mapped;rr()}}}
 function search(){const list=Slotelly.filterClients(q.value);res.innerHTML=list.slice(0,25).map(c=>`<button type="button" class="card pick" data-id="${c.id}"><b>${esc(cname(c))}</b><div class="sub">${esc(c.phone||'')}</div></button>`).join('')||'<div class="sub">Клиент не найден</div>';res.querySelectorAll('.pick').forEach(b=>b.onclick=()=>pick(Slotelly.clients.find(c=>String(c.id)===String(b.dataset.id))))}
 q.oninput=()=>{cid='';chosenClient=null;if(q.value.trim().length<2){res.innerHTML='';return}search()};q.onfocus=()=>{if(q.value.trim().length>=2)search()};document.getElementById('addSvc').onclick=()=>{rows.push({service_id:'',name:'',standard_price:0,price:0,duration:60});rr()};
 const nc=document.getElementById('newC');if(nc)nc.onclick=()=>newClient(c=>{pick(c)});
 save.onclick=async()=>{err.textContent='';if(!cid){const exact=Slotelly.filterClients(q.value).filter(c=>cname(c).toLowerCase()===q.value.trim().toLowerCase());if(exact.length===1)pick(exact[0]);else{err.textContent='Выберите клиента из списка';return}}if(rows.some(r=>!r.service_id)){err.textContent='Выберите услугу';return}const starts=new Date(document.getElementById('date').value+'T'+document.getElementById('time').value+':00+03:00').toISOString(),mins=rows.reduce((n,r)=>n+Number(r.duration||0),0)+30,ends=new Date(new Date(starts).getTime()+mins*60000).toISOString(),payload={id:a?.id||null,client_id:cid,starts_at:starts,services:rows,comment:document.getElementById('com').value,status:a?.status||'new'},optimistic={client_id:cid,client_name:q.value.trim()||cname(chosenClient),starts_at:starts,ends_at:ends,status:a?.status||'new',master_comment:payload.comment,services:rows};closeModal();renderCal();const r=await Slotelly.saveAppointment(payload,optimistic);if(!r.queued&&typeof window.notifyApi==='function'&&!a)window.notifyApi('sendAppointment',{appointmentId:r.id,templateType:'confirmation'}).catch(()=>{})};
};
window.newClient=function(done){modal('Новый клиент','',`<div class="field"><input id="nn" placeholder="Имя"></div><div class="field"><input id="np" placeholder="Телефон" type="tel"></div><div class="field"><select id="nm"><option>Telegram</option><option>WhatsApp</option><option>VK</option><option>MAX</option></select></div>`,'<button class="btn primary" id="ns">Сохранить</button>');document.getElementById('ns').onclick=async()=>{const b=document.getElementById('ns');b.disabled=true;b.textContent='Сохраняю…';try{const c=await Slotelly.createClient({name:document.getElementById('nn').value,phone:document.getElementById('np').value,messenger:document.getElementById('nm').value});closeModal();done?.(c)}catch(e){b.disabled=false;b.textContent='Сохранить';alert(e.message)}}};
window.showAppt=function(a){const total=(a.services||[]).reduce((n,s)=>n+Number(s.price||0),0),p=a.payments?.[0];modal(a.client_name||'Запись',`${localDate(a.starts_at)} · ${localTime(a.starts_at)}`,`<button class="card" id="clientLink"><b>${esc(a.client_name||'Клиент')}</b></button><div class="card">${(a.services||[]).map(s=>`${esc(s.name)} — <b>${Number(s.price||0).toLocaleString('ru-RU')} ₽</b>`).join('<br>')}<hr>Итого <b>${total.toLocaleString('ru-RU')} ₽</b></div><div class="card">Комментарий: ${esc(a.master_comment||'—')}</div><div class="card">Оплата: ${p?Number(p.total).toLocaleString('ru-RU')+' ₽':'не проведена'}</div>`,'<button class="btn primary" id="edit">Редактировать</button><button class="btn" id="pay">Оплатить</button><button class="btn" id="unpaid">Без оплаты</button><button class="btn" id="cancelA">Отменить</button>');document.getElementById('edit').onclick=()=>form(a,localDate(a.starts_at),localTime(a.starts_at));document.getElementById('pay').onclick=()=>payment(a,total);document.getElementById('unpaid').onclick=()=>{closeModal();Slotelly.status(a.id,'completed_unpaid');renderCal()};document.getElementById('cancelA').onclick=()=>{if(confirm('Отменить запись?')){closeModal();Slotelly.status(a.id,'cancelled');renderCal()}}};
window.payment=function(a,total){modal('Оплата',a.client_name||'',`<div class="field"><label>Наличные</label><input id="cash" type="number" value="0"></div><div class="field"><label>Карта</label><input id="card" type="number" value="${total}"></div><div class="field"><label>Другое</label><input id="other" type="number" value="0"></div>`,'<button class="btn primary" id="ps">Провести</button>');document.getElementById('ps').onclick=()=>{const c=Number(cash.value||0),d=Number(card.value||0),o=Number(other.value||0);if(c+d+o!==total)return alert('Разбивка должна быть '+total+' ₽');closeModal();Slotelly.payment(a.id,c,d,o);renderCal()}};
window.loadClients=async function(){const box=document.getElementById('clientList'),search=document.getElementById('clientSearch');function draw(){const list=Slotelly.filterClients(search.value.trim());box.innerHTML=list.map(c=>`<button class="client-row cli-local" data-id="${c.id}"><span class="client-avatar">${esc(cname(c).charAt(0).toUpperCase()||'•')}</span><span class="client-main"><b>${esc(cname(c))}</b><span class="sub">${esc(c.phone||'')}</span></span></button>`).join('')||'<div class="sub">Ничего не найдено</div>';box.querySelectorAll('.cli-local').forEach(b=>b.onclick=()=>clientCard(b.dataset.id))}search.oninput=draw;if(Slotelly.clients.length)draw();else{box.innerHTML='<div class="sub">Клиенты загружаются один раз…</div>';Slotelly.syncClients().then(draw).catch(()=>{box.innerHTML='<div class="sub">Клиенты появятся после восстановления связи</div>'})}};
const oldClientCard=window.clientCard;window.clientCard=function(id){const c=Slotelly.clients.find(x=>String(x.id)===String(id));if(!c&&oldClientCard)return oldClientCard(id);const hist=(Slotelly.calendar().appointments||[]).filter(a=>String(a.client_id)===String(id)).sort((a,b)=>new Date(b.starts_at)-new Date(a.starts_at));modal(cname(c),'Карточка клиента',`<div class="card">Телефон: <b>${esc(c?.phone||'')}</b></div><div class="list">${hist.map(h=>`<button class="card hist-local" data-id="${h.id}"><b>${localDate(h.starts_at)} ${localTime(h.starts_at)}</b><div class="sub">${esc((h.services||[]).map(s=>s.name).join(' + '))} · ${h.status}</div></button>`).join('')}</div>`);document.querySelectorAll('.hist-local').forEach(b=>b.onclick=()=>showAppt((Slotelly.calendar().appointments||[]).find(a=>String(a.id)===String(b.dataset.id))))};
window.screen=function(id){$$('.screen').forEach(x=>x.classList.toggle('on',x.id===id));$$('.bottomnav button').forEach(x=>x.classList.toggle('active',x.dataset.s===id));if(id==='calendar'){renderCal();Slotelly.sync(focus,false).catch(()=>{})}else if(id==='clients')loadClients();else if(id==='finance'&&typeof runFinance==='function')runFinance();else if(id==='reports'&&typeof loadReports==='function')loadReports();else if(id==='services'&&typeof renderServices==='function')renderServices();else if(id==='settings'&&typeof renderSettings==='function')renderSettings()};
$$('.bottomnav button').forEach(b=>b.onclick=()=>screen(b.dataset.s));$$('.homebtn').forEach(b=>b.onclick=()=>screen(b.dataset.go));bind('newBtn',()=>form(null,focus,'16:00'));
renderCal();Slotelly.sync(focus,false).catch(()=>{});
})();