/* Slotelly Runtime v2 — local-first, instant mutations, stale-sync protection. */
(()=>{'use strict';
const BASE='https://acukaqoguzkrphauovhk.supabase.co',KEY='sb_publishable_2aKxmTx4WtnZglspnun9gA_goe71amD',RPC=BASE+'/rest/v1/rpc/slotelly_mobile_api',STORE_KEY='slotelly_runtime_v1',CLIENTS_KEY='slotelly_clients_v1',OUTBOX_KEY='slotelly_outbox_v1',DAY=86400000;
const now=()=>Date.now(),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
let state=read(STORE_KEY,{services:[],settings:{},calendar:{appointments:[],blocks:[],overrides:[]},from:null,to:null,waitlist_count:0,_cached_at:0}),clients=read(CLIENTS_KEY,[]),outbox=read(OUTBOX_KEY,[]),syncPromise=null,clientsPromise=null,flushing=false;const listeners=new Set(),normPhone=x=>String(x||'').replace(/\D/g,'').replace(/^8(?=\d{10}$)/,'7');
const emit=()=>{window.SLOTELLY_STATE=state;window.SLOTELLY_SNAPSHOT={ok:true,...state,clients};try{if(Array.isArray(state.services))window.services=state.services;if(state.settings)window.settings=state.settings}catch{};listeners.forEach(fn=>{try{fn(state)}catch{}});window.dispatchEvent(new CustomEvent('slotelly:state',{detail:state}))},saveState=()=>{state._cached_at=now();write(STORE_KEY,state);emit()},saveClients=()=>{write(CLIENTS_KEY,clients);emit()};
async function rpc(action,data={},timeout=12000){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(RPC,{method:'POST',headers:{'Content-Type':'application/json','apikey':KEY,'Authorization':'Bearer '+KEY},body:JSON.stringify({p_pin:PIN,p_action:action,p_data:data}),signal:ctl.signal,cache:'no-store'}),text=await r.text();let j;try{j=text?JSON.parse(text):null}catch{throw Error(text||'Ошибка сервера')}if(!r.ok)throw Error(j?.message||j?.error||'Ошибка сервера');return j}catch(e){if(e?.name==='AbortError')throw Error('Синхронизация не завершена');throw e}finally{clearTimeout(timer)}}
function range(center){const d=new Date(center+'T12:00:00+03:00');return{from:new Date(d.getTime()-21*DAY).toISOString(),to:new Date(d.getTime()+43*DAY).toISOString()}}
function applyPending(){for(const item of outbox){const p=item.payload||{};if(item.kind==='set_status')patchAppointment(p.id,{status:p.status,_pending:true},false);else if(item.kind==='payment')patchAppointment(p.id,{status:'completed_paid',payments:[{total:Number(p.cash)+Number(p.card)+Number(p.other),cash:p.cash,card:p.card,other:p.other}],_pending:true},false);else if(item.kind==='availability')setAvailability(p.slot,p.value,false)}}
function mergeSnapshot(j){if(!j)return;state={...state,...j,calendar:j.calendar||state.calendar||{appointments:[],blocks:[],overrides:[]},_cached_at:now()};applyPending();saveState()}
async function sync(center=(window.focus||new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'})),force=false){if(syncPromise)return syncPromise;if(!force&&state._cached_at&&now()-state._cached_at<45000)return state;syncPromise=rpc('snapshot',{...range(center),include_clients:false},15000).then(j=>{mergeSnapshot(j);return state}).finally(()=>syncPromise=null);return syncPromise}
async function syncClients(force=false){if(clientsPromise)return clientsPromise;if(!force&&clients.length)return clients;clientsPromise=rpc('clients',{},15000).then(j=>{clients=Array.isArray(j?.clients)?j.clients:[];saveClients();return clients}).finally(()=>clientsPromise=null);return clientsPromise}
function filterClients(q=''){const s=String(q||'').trim().toLowerCase(),d=normPhone(q);if(!s)return clients;return clients.filter(c=>String(c.display_name||c.name||'').toLowerCase().includes(s)||(d&&normPhone(c.phone).includes(d)))}
function upsertAppointment(a,save=true){if(!a?.id)return;const cal=state.calendar||(state.calendar={appointments:[],blocks:[],overrides:[]}),arr=cal.appointments||(cal.appointments=[]),i=arr.findIndex(x=>String(x.id)===String(a.id));if(i>=0)arr[i]={...arr[i],...a};else arr.push(a);arr.sort((x,y)=>new Date(x.starts_at)-new Date(y.starts_at));if(save)saveState()}
function patchAppointment(id,patch,save=true){const a=(state.calendar?.appointments||[]).find(x=>String(x.id)===String(id));if(a){Object.assign(a,patch);if(save)saveState()}}
function setAvailability(slot,value,save=true){const arr=state.calendar?.overrides||(state.calendar.overrides=[]),i=arr.findIndex(x=>new Date(x.slot_start).getTime()===new Date(slot).getTime()),row={slot_start:slot,is_available:!!value,reason:value?'manual_on':'manual_off'};if(i>=0)arr[i]={...arr[i],...row};else arr.push(row);if(save)saveState()}
function queue(kind,payload){const same=outbox.find(x=>x.kind===kind&&payload.id&&x.payload?.id===payload.id);if(same){same.payload=payload;same.created_at=now()}else outbox.push({id:'q'+now()+Math.random().toString(36).slice(2),kind,payload,created_at:now(),tries:0});write(OUTBOX_KEY,outbox);queueMicrotask(flush);return true}
async function send(item){if(item.kind==='save_appointment')return rpc('save_appointment',item.payload,20000);if(item.kind==='set_status')return rpc('set_status',item.payload,12000);if(item.kind==='payment')return rpc('payment',item.payload,12000);if(item.kind==='availability')return rpc('availability',item.payload,12000);if(item.kind==='create_client')return rpc('create_client',item.payload,12000);throw Error('Неизвестная операция')}
async function flush(){if(flushing||!outbox.length||!navigator.onLine)return;flushing=true;try{for(const item of [...outbox]){try{const j=await send(item);outbox=outbox.filter(x=>x.id!==item.id);write(OUTBOX_KEY,outbox);if(item.kind==='set_status'||item.kind==='payment')patchAppointment(item.payload.id,{_pending:false},true);window.dispatchEvent(new CustomEvent('slotelly:outbox-sent',{detail:{item,result:j}}))}catch(e){item.tries=(item.tries||0)+1;item.error=String(e?.message||e);write(OUTBOX_KEY,outbox);break}}}finally{flushing=false}}
async function saveAppointment(payload,optimistic){const tempId=payload.id||('local-'+crypto.randomUUID());upsertAppointment({...optimistic,id:tempId,_pending:true});try{const j=await rpc('save_appointment',payload,20000);if(!payload.id&&j?.id){const arr=state.calendar.appointments||[],i=arr.findIndex(x=>x.id===tempId);if(i>=0)arr.splice(i,1);upsertAppointment({...optimistic,id:j.id,ends_at:j.ends_at||optimistic.ends_at,_pending:false})}else patchAppointment(payload.id,{...optimistic,_pending:false});return{ok:true,id:j?.id||payload.id,queued:false}}catch(e){queue('save_appointment',payload);patchAppointment(tempId,{_pending:true,_sync_error:true});return{ok:true,id:tempId,queued:true,error:e?.message||'Ожидает синхронизации'}}}
function status(id,status){patchAppointment(id,{status,_pending:true});queue('set_status',{id,status});return Promise.resolve({queued:true,local:true})}
function payment(id,cash,card,other){patchAppointment(id,{status:'completed_paid',payments:[{total:Number(cash)+Number(card)+Number(other),cash,card,other}],_pending:true});queue('payment',{id,cash,card,other});return Promise.resolve({queued:true,local:true})}
function availability(slot,value){setAvailability(slot,value);queue('availability',{slot,value});return Promise.resolve({queued:true,local:true})}
async function createClient(data){try{const c=await rpc('create_client',data,15000),i=clients.findIndex(x=>String(x.id)===String(c.id));if(i>=0)clients[i]={...clients[i],...c};else clients.push(c);saveClients();return c}catch{throw Error('Для создания нового клиента сейчас нужна связь с сервером')}}
function calendar(){return state.calendar||{appointments:[],blocks:[],overrides:[]}}
window.Slotelly={get state(){return state},get clients(){return clients},calendar,filterClients,sync,syncClients,saveAppointment,status,payment,availability,createClient,upsertAppointment,patchAppointment,flush,on(fn){listeners.add(fn);return()=>listeners.delete(fn)},rpc};emit();window.addEventListener('online',()=>{flush();sync(window.focus,true).catch(()=>{});syncClients(true).catch(()=>{})});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){flush();sync(window.focus,false).catch(()=>{})}});setTimeout(()=>{sync(window.focus,false).catch(()=>{});if(!clients.length)syncClients(false).catch(()=>{});flush()},0);
})();