/* Client waitlist controls */
const WAIT_EDGE='https://acukaqoguzkrphauovhk.supabase.co/functions/v1/resnitsy-waitlist';
async function waitApi(action,data={}){const r=await fetch(WAIT_EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:PIN,action,...data})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Ошибка ловца окошек');return j}
function fmtWaitDate(x){if(!x)return '—';return new Date(x+'T00:00:00').toLocaleDateString('ru-RU')}
window.clientCard=async function(id){
  const [d,w]=await Promise.all([edge('history',{clientId:id}),waitApi('list',{clientId:id})]);
  const c=d.client, active=(w.rows||[]).find(x=>x.status==='active'||x.status==='new');
  const done=d.history.filter(x=>x.status==='completed_paid'||x.status==='completed_unpaid');
  const last=done.length?new Date(done[0].starts_at).toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow'}):'—';
  const waitBlock=active?`<div class="card" style="margin-top:8px"><b>Ловец окошек включён</b><div class="sub">${active.desired_text||'Без услуги'} · ${fmtWaitDate(active.date_from)} — ${fmtWaitDate(active.date_to)}${active.time_from||active.time_to?` · ${String(active.time_from||'').slice(0,5)}–${String(active.time_to||'').slice(0,5)}`:''}</div></div>`:'';
  modal(c.display_name,'Карточка клиента',`<div class="card">Телефон: <b>${c.phone||'—'}</b><br>Последний визит: <b>${last}</b></div>${waitBlock}<button class="btn primary" id="clientWaitBtn" style="width:100%;margin-top:8px">${active?'Настроить ловца окошек':'Включить ловца окошек'}</button><div class="list" style="margin-top:8px">${d.history.map(h=>`<button class="card hist" data-id="${h.id}"><b>${new Date(h.starts_at).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})}</b><div class="sub">${h.appointment_services.map(s=>s.service_name_snapshot).join(' + ')} · ${h.status}</div></button>`).join('')}</div>`);
  document.querySelectorAll('.hist').forEach(b=>b.onclick=async()=>{const a=(await edge('appointment',{id:b.dataset.id})).appointment;showAppt({id:a.id,client_id:a.client_id,client_name:a.clients?.display_name,starts_at:a.starts_at,ends_at:a.ends_at,status:a.status,master_comment:a.master_comment,services:a.appointment_services.map(s=>({service_id:s.service_id,name:s.service_name_snapshot,standard_price:s.standard_price_snapshot,price:s.actual_price,duration:s.duration_minutes})),payments:(a.payments||[]).map(p=>({total:p.total_amount}))})});
  document.getElementById('clientWaitBtn').onclick=()=>waitlistForm(c,active);
};
async function waitlistForm(client,row=null){
  let svc=services;
  if(!svc?.length){try{const z=await serviceApi('list');svc=z.services||[];services=svc}catch{svc=[]}}
  const activeSvc=svc.filter(s=>s.is_active!==false);
  const selectedName=row?.desired_text||activeSvc[0]?.name||'';
  const messenger=row?.preferred_messenger||client.messenger||'Telegram';
  modal('Ловец окошек',client.display_name||'',`<div class="field"><label>Услуга</label><select id="wlService">${activeSvc.map(s=>`<option ${s.name===selectedName?'selected':''}>${s.name}</option>`).join('')}</select></div><div class="twocol"><div class="field"><label>Дата с</label><input id="wlFrom" type="date" value="${row?.date_from||todayStr()}"></div><div class="field"><label>Дата по</label><input id="wlTo" type="date" value="${row?.date_to||add(todayStr(),14)}"></div></div><div class="twocol"><div class="field"><label>Время с</label><input id="wlTimeFrom" type="time" value="${String(row?.time_from||'10:00').slice(0,5)}"></div><div class="field"><label>Время по</label><input id="wlTimeTo" type="time" value="${String(row?.time_to||'20:00').slice(0,5)}"></div></div><div class="field"><label>Мессенджер</label><select id="wlMessenger"><option ${messenger==='Telegram'?'selected':''}>Telegram</option><option ${messenger==='WhatsApp'?'selected':''}>WhatsApp</option><option ${messenger==='VK'?'selected':''}>VK</option><option ${messenger==='MAX'?'selected':''}>MAX</option></select></div><div id="wlErr" class="sub" style="color:#a33;min-height:18px"></div>`,`<button class="btn primary" id="wlSave">Сохранить</button>${row?'<button class="btn" id="wlOff">Выключить ловца</button>':''}`);
  const save=document.getElementById('wlSave'),err=document.getElementById('wlErr');
  save.onclick=async()=>{err.textContent='';const f=document.getElementById('wlFrom').value,t=document.getElementById('wlTo').value;if(!f||!t)return err.textContent='Укажите период';if(f>t)return err.textContent='Дата «с» позже даты «по»';save.disabled=true;save.textContent='Сохраняю…';try{await waitApi('save',{id:row?.id||null,clientId:client.id,desiredText:document.getElementById('wlService').value,dateFrom:f,dateTo:t,timeFrom:document.getElementById('wlTimeFrom').value||null,timeTo:document.getElementById('wlTimeTo').value||null,messenger:document.getElementById('wlMessenger').value,status:'active'});closeModal();await clientCard(client.id)}catch(e){err.textContent=e.message;save.disabled=false;save.textContent='Сохранить'}};
  const off=document.getElementById('wlOff');if(off)off.onclick=async()=>{if(confirm('Выключить ловца окошек для клиента?')){await waitApi('status',{id:row.id,status:'closed'});closeModal();await clientCard(client.id)}};
}
