/* Client waitlist controls + clear visit statuses */
const WAIT_EDGE='https://acukaqoguzkrphauovhk.supabase.co/functions/v1/resnitsy-waitlist';
async function waitApi(action,data={}){const r=await fetch(WAIT_EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin:PIN,action,...data})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Ошибка ловца окошек');return j}
function fmtWaitDate(x){if(!x)return '—';return new Date(x+'T00:00:00').toLocaleDateString('ru-RU')}
function visitStatus(h){const s=String(h.status||'').toLowerCase(),start=new Date(h.starts_at),now=new Date();if(s==='cancelled'||s==='canceled')return ['Отменён','cancel'];if(s==='completed_paid'||s==='completed_unpaid'||s==='completed')return ['Завершён','done'];if(start>now){if(s==='confirmed'||s==='confirmed_master'||s==='confirmed_client')return ['Подтверждён','confirm'];return ['Предстоящая','future']}if(s==='new')return ['Новый','new'];if(s==='imported')return ['Завершён','done'];return start<=now?['Завершён','done']:['Предстоящая','future']}
window.clientCard=async function(id){
 const [d,w]=await Promise.all([edge('history',{clientId:id}),waitApi('list',{clientId:id})]);const c=d.client,active=(w.rows||[]).find(x=>['active','new','offered'].includes(x.status));
 const waitBlock=active?`<div class="card" style="margin-top:8px"><b>Ловец окошек включён</b><div class="sub">${active.desired_text||'Без услуги'} · ${fmtWaitDate(active.date_from)} — ${fmtWaitDate(active.date_to)}${active.time_from||active.time_to?` · ${String(active.time_from||'').slice(0,5)}–${String(active.time_to||'').slice(0,5)}`:''}</div></div>`:'';
 const visits=(d.history||[]).map(h=>{const [label,cl]=visitStatus(h),dt=new Date(h.starts_at).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}),sv=(h.appointment_services||[]).map(s=>s.service_name_snapshot).join(' + ')||'Без услуги';return `<button class="card hist client-visit" data-id="${h.id}"><div class="visit-head"><b>${dt}</b><span class="visit-status ${cl}">${label}</span></div><div class="sub">${sv}</div></button>`}).join('');
 modal(c.display_name,'Карточка клиента',`<div class="card">Телефон: <b>${c.phone||'—'}</b></div>${waitBlock}<button class="btn primary" id="clientWaitBtn" style="width:100%;margin-top:8px">${active?'Настроить ловца окошек':'Включить ловца окошек'}</button><div class="client-history-title">История визитов</div><div class="list">${visits||'<div class="sub">Визитов пока нет</div>'}</div><style>.client-history-title{font-weight:800;margin:14px 2px 7px}.visit-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.visit-status{font-size:10px;font-weight:750;padding:4px 8px;border-radius:999px;white-space:nowrap}.visit-status.done{background:#e9f6ed;color:#337044}.visit-status.future,.visit-status.confirm{background:#eee7f3;color:#714b76}.visit-status.new{background:#fff0f5;color:#b3265d}.visit-status.cancel{background:#f1f1f1;color:#888}.client-visit{text-align:left}</style>`);
 document.querySelectorAll('.hist').forEach(b=>b.onclick=async()=>{const a=(await edge('appointment',{id:b.dataset.id})).appointment;showAppt({id:a.id,client_id:a.client_id,client_name:a.clients?.display_name,starts_at:a.starts_at,ends_at:a.ends_at,status:a.status,master_comment:a.master_comment,services:a.appointment_services.map(s=>({service_id:s.service_id,name:s.service_name_snapshot,standard_price:s.standard_price_snapshot,price:s.actual_price,duration:s.duration_minutes})),payments:(a.payments||[]).map(p=>({total:p.total_amount}))})});document.getElementById('clientWaitBtn').onclick=()=>waitlistForm(c,active);
};
async function waitlistForm(client,row=null){let svc=services;if(!svc?.length){try{const z=await serviceApi('list');svc=z.services||[];services=svc}catch{svc=[]}}const activeSvc=svc.filter(s=>s.is_active!==false),selectedName=row?.desired_text||activeSvc[0]?.name||'',messenger=row?.preferred_messenger||client.messenger||'Telegram';modal('Ловец окошек',client.display_name||'',`<div class="field"><label>Услуга</label><select id="wlService">${activeSvc.map(s=>`<option ${s.name===selectedName?'selected':''}>${s.name}</option>`).join('')}</select></div><div class="twocol"><div class="field"><label>Дата с</label><input id="wlFrom" type="date" value="${row?.date_from||todayStr()}"></div><div class="field"><label>Дата по</label><input id="wlTo" type="date" value="${row?.date_to||add(todayStr(),14)}"></div></div><div class="twocol"><div class="field"><label>Время с</label><input id="wlTimeFrom" type="time" value="${String(row?.time_from||'10:00').slice(0,5)}"></div><div class="field"><label>Время по</label><input id="wlTimeTo" type="time" value="${String(row?.time_to||'20:00').slice(0,5)}"></div></div><div class="field"><label>Мессенджер</label><select id="wlMessenger"><option ${messenger==='Telegram'?'selected':''}>Telegram</option><option ${messenger==='WhatsApp'?'selected':''}>WhatsApp</option><option ${messenger==='VK'?'selected':''}>VK</option><option ${messenger==='MAX'?'selected':''}>MAX</option></select></div><div id="wlErr" class="sub" style="color:#a33;min-height:18px"></div>`,`<button class="btn primary" id="wlSave">Сохранить</button>${row?'<button class="btn" id="wlOff">Выключить ловца</button>':''}`);const save=document.getElementById('wlSave'),err=document.getElementById('wlErr');save.onclick=async()=>{err.textContent='';const f=wlFrom.value,t=wlTo.value;if(!f||!t)return err.textContent='Укажите период';if(f>t)return err.textContent='Дата «с» позже даты «по»';save.disabled=true;try{await waitApi('save',{id:row?.id||null,clientId:client.id,desiredText:wlService.value,dateFrom:f,dateTo:t,timeFrom:wlTimeFrom.value||null,timeTo:wlTimeTo.value||null,messenger:wlMessenger.value,status:'active'});closeModal();await clientCard(client.id)}catch(e){err.textContent=e.message;save.disabled=false}};const off=document.getElementById('wlOff');if(off)off.onclick=async()=>{if(confirm('Выключить ловца окошек для клиента?')){await waitApi('cancel',{id:row.id});closeModal();await clientCard(client.id)}}}
