/* Per-master working time. DIKIDI-like grouped schedules; identical schedules merge automatically. */
(function(){
 const defs=[[1,'Пн'],[2,'Вт'],[3,'Ср'],[4,'Чт'],[5,'Пт'],[6,'Сб'],[0,'Вс']];let groups=[];
 function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function mergeSame(gs){const map=new Map();(gs||[]).forEach((g,i)=>{const times=[...new Set(g.times||[])].sort(),key=times.join('|');if(!key)return;const days=[...new Set(g.days||[])];if(map.has(key)){const x=map.get(key);x.days=[...new Set([...x.days,...days])].sort((a,b)=>a-b)}else map.set(key,{id:g.id||('g'+i),days:[...days],times})});return [...map.values()].filter(g=>g.days.length)}
 async function load(){const z=await dayoffApi('weekly');weeklyWorkdays=Array.isArray(z.weekdays)?z.weekdays:[];groups=mergeSame(Array.isArray(z.work_time_groups)?z.work_time_groups:[]);return z}
 function dayTimesByNumber(d,excludeId=null){return [...new Set(groups.filter(g=>g.id!==excludeId&&(g.days||[]).includes(d)).flatMap(g=>g.times||[]))].sort()}
 function dayTimes(ds){return dayTimesByNumber(weekdayOf(ds))}
 function localDate(iso){return new Date(iso).toLocaleDateString('sv-SE',{timeZone:'Europe/Moscow'})}function localTime(iso){return new Date(iso).toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'})}
 const prevWeek=window.renderWeekV4;window.renderWeekV4=async function(){await load();const out=await prevWeek.apply(this,arguments);const cols=[...document.querySelectorAll('#week .day')],h=Math.max(420,document.getElementById('week').clientHeight||520);cols.forEach((col,i)=>{const ds=add(weekStart,i);col.querySelectorAll('.free').forEach(x=>x.remove());if(isDayOff(lastCal,ds))return;const aps=(lastCal.appointments||[]).filter(a=>ld(a.starts_at)===ds&&a.status!=='cancelled'),ovs=(lastCal.overrides||[]).filter(o=>localDate(o.slot_start)===ds),openCustom=ovs.filter(o=>o.is_available).map(o=>localTime(o.slot_start)),times=[...new Set([...dayTimes(ds),...openCustom])].sort();times.forEach(t=>{const iso=new Date(ds+'T'+t+':00+03:00').toISOString(),o=ovs.find(x=>new Date(x.slot_start).getTime()===new Date(iso).getTime());if(o&&o.is_available===false)return;const moment=new Date(iso);if(aps.some(a=>moment>=new Date(a.starts_at)&&moment<new Date(a.ends_at)))return;const m=Number(t.slice(0,2))*60+Number(t.slice(3)),b=document.createElement('button');b.className='free';b.style.top=(42+(m-540)/840*(h-42))+'px';b.textContent=t;b.onclick=e=>{e.stopPropagation();focus=ds;view='day';renderCal()};col.appendChild(b)})});return out};
 function groupCard(g){return `<div class="wt-group" data-id="${esc(g.id)}"><div class="wt-group-days">${defs.map(([n,l])=>`<span class="wt-group-day ${(g.days||[]).includes(n)?'on':''}">${l}</span>`).join('')}</div><div class="wt-time-chips">${(g.times||[]).map(t=>`<span>${t}</span>`).join('')}</div><div class="wt-group-actions"><button class="btn wt-delete" data-id="${esc(g.id)}" title="Удалить">🗑</button><button class="btn wt-edit" data-id="${esc(g.id)}">Изменить время</button></div></div>`}
 function block(){const card=document.createElement('div');card.className='card dayoff-settings-block wt-settings';card.dataset.worktime='1';card.innerHTML='<b>Фиксированное время записи</b><div class="sub">Укажите время для дней недели, на которое клиенты смогут записываться. Для разных дней можно задать разное время.</div><div id="wtList" class="wt-groups">'+(groups.length?groups.map(groupCard).join(''):'<div class="wt-empty"><b>Рабочее время не настроено</b><div class="sub">Создайте первый режим.</div></div>')+'</div><button class="btn primary" id="wtAdd" style="width:100%;margin-top:12px">+ Добавить дни недели</button>';return card}
 function bindBlock(){document.querySelectorAll('.wt-edit').forEach(b=>b.onclick=()=>edit(b.dataset.id));document.querySelectorAll('.wt-delete').forEach(b=>b.onclick=async()=>{const id=b.dataset.id;if(!confirm('Удалить этот режим?'))return;groups=groups.filter(g=>g.id!==id);await persist();await renderSettings()});document.getElementById('wtAdd')?.addEventListener('click',()=>edit(null))}
 function timesHtml(ts){return ts.map(t=>`<div class="wt-time-row"><input type="time" step="900" class="wt-time" value="${esc(t)}"><button type="button" class="btn wt-del-time">×</button></div>`).join('')}
 function edit(id){const old=groups.find(g=>g.id===id),days=[...(old?.days||[])],times=[...(old?.times||[])];let timesDirty=false;
 modal(id?'Фиксированное время':'Новое фиксированное время','Выберите дни недели и время записи',`<div class="wt-days">${defs.map(([n,l])=>`<label class="wt-day ${days.includes(n)?'on':''}"><input type="checkbox" value="${n}" ${days.includes(n)?'checked':''}><span>${l}</span></label>`).join('')}</div><div id="wtSelectedDays" class="wt-selected-days"></div><div class="sub" style="margin:12px 0 6px">Время начала записей</div><div id="wtTimes">${timesHtml(times)}</div><button type="button" class="btn" id="wtAddTime" style="width:100%;margin-top:6px">+ Добавить время</button>`,`<button class="btn primary" id="wtSave">Сохранить</button><button class="btn" id="wtCancel">Отмена</button>`);
 function selected(){return [...document.querySelectorAll('.wt-day input:checked')].map(x=>Number(x.value))}
 function bindTimes(){document.querySelectorAll('.wt-del-time').forEach(b=>b.onclick=()=>{timesDirty=true;b.closest('.wt-time-row').remove()});document.querySelectorAll('.wt-time').forEach(i=>i.oninput=()=>timesDirty=true)}
 function refill(ts){const box=document.getElementById('wtTimes');if(!box)return;box.innerHTML=timesHtml(ts);bindTimes()}
 function updateSelected(fromClick=false){const sel=selected(),names=defs.filter(([n])=>sel.includes(n)).map(([,l])=>l),box=document.getElementById('wtSelectedDays');if(box)box.innerHTML=names.length?`<span>Выбрано:</span><b>${names.join(' · ')}</b>`:'<span>Дни не выбраны</span>';
   if(!timesDirty&&sel.length){const schedules=sel.map(n=>{if(old?.days?.includes(n))return [...(old.times||[])];return dayTimesByNumber(n,id)}).filter(x=>x.length);if(schedules.length){const first=schedules[0].join('|'),same=schedules.every(x=>x.join('|')===first);if(same)refill(schedules[0]);else if(fromClick)refill([])}else if(fromClick&&!id)refill([])}
 }
 bindTimes();document.querySelectorAll('.wt-day input').forEach(x=>x.onchange=()=>{x.closest('.wt-day').classList.toggle('on',x.checked);timesDirty=false;updateSelected(true)});updateSelected(false);wtAddTime.onclick=()=>{timesDirty=true;wtTimes.insertAdjacentHTML('beforeend',timesHtml(['10:00']));bindTimes()};wtCancel.onclick=closeModal;wtSave.onclick=async()=>{const sel=selected(),ts=[...new Set([...document.querySelectorAll('.wt-time')].map(x=>x.value).filter(Boolean))].sort();if(!sel.length)return alert('Выберите хотя бы один день');if(!ts.length)return alert('Добавьте хотя бы одно время');groups=groups.filter(g=>g.id!==id).map(g=>({...g,days:(g.days||[]).filter(d=>!sel.includes(d))})).filter(g=>g.days.length);groups.push({id:id||('g'+Date.now()),days:sel,times:ts});groups=mergeSame(groups);await persist();closeModal();await renderSettings()}}
 async function persist(){groups=mergeSame(groups);const z=await dayoffApi('setWorkTime',{groups});groups=mergeSame(z.work_time_groups||groups);weeklyWorkdays=z.weekdays||[...new Set(groups.flatMap(g=>g.days||[]))]}
 const prevSettings=window.renderSettings;window.renderSettings=async function(){await prevSettings.apply(this,arguments);await load();const box=document.getElementById('settingsBox');if(!box)return;box.querySelectorAll('[data-worktime]').forEach(x=>x.remove());const card=block(),weekly=box.querySelector('.dayoff-settings-block');if(weekly)weekly.insertAdjacentElement('afterend',card);else box.appendChild(card);bindBlock()};
 const st=document.createElement('style');st.textContent='.wt-groups{margin-top:12px}.wt-group{padding:14px 0;border-bottom:1px solid var(--line)}.wt-group:first-child{padding-top:4px}.wt-group-days{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.wt-group-day{border:1px solid var(--line);border-radius:10px;padding:8px 2px;text-align:center;color:var(--muted);background:#fff}.wt-group-day.on{background:var(--accent);border-color:var(--accent);color:#fff;font-weight:700}.wt-time-chips{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.wt-time-chips span{padding:7px 11px;border-radius:999px;background:#eee;font-size:14px}.wt-group-actions{display:grid;grid-template-columns:52px 1fr;gap:8px}.wt-delete{color:#c44}.wt-empty{padding:12px;border:1px dashed var(--line);border-radius:10px}.wt-days{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.wt-day{border:1px solid var(--line);border-radius:10px;padding:9px 2px;text-align:center}.wt-day input{display:none}.wt-day.on{background:var(--soft);border-color:var(--accent);font-weight:700}.wt-selected-days{margin:10px 0 4px;padding:10px 12px;border-radius:10px;background:var(--soft);display:flex;gap:6px;align-items:center;flex-wrap:wrap}.wt-selected-days span{color:var(--muted);font-size:13px}.wt-selected-days b{font-size:14px}.wt-time-row{display:grid;grid-template-columns:1fr 44px;gap:6px;margin:6px 0}.wt-time-row input{width:100%}';document.head.appendChild(st)
})();